// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Details of the Autonomous Database resource.
/// https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/AutonomousDatabase/
public struct AutonomousDatabase: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the Autonomous Database resource in the following
  /// format:
  /// projects/{project}/locations/{region}/autonomousDatabases/{autonomous_database}
  public var name: Swift.String = Swift.String()

  /// Optional. Immutable. The name of the Autonomous Database. The database name
  /// must be unique in the project. The name must begin with a letter and can
  /// contain a maximum of 30 alphanumeric characters.
  public var database: Swift.String = Swift.String()

  /// Optional. Immutable. The display name for the Autonomous Database. The name
  /// does not have to be unique within your project.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The ID of the subscription entitlement associated with the
  /// Autonomous Database.
  public var entitlementId: Swift.String = Swift.String()

  /// Optional. Immutable. The password for the default ADMIN user.
  /// Note: Only one of `admin_password_secret_version` or `admin_password` can
  /// be populated.
  public var adminPassword: Swift.String = Swift.String()

  /// Optional. Immutable. The resource name of a secret version in Secret
  /// Manager which contains the database admin user's password. Format:
  /// projects/{project}/secrets/{secret}/versions/{version}. Note: Only one of
  /// `admin_password_secret_version` or `admin_password` can be populated.
  public var adminPasswordSecretVersion: Swift.String = Swift.String()

  /// Optional. The properties of the Autonomous Database.
  public var properties: AutonomousDatabaseProperties? = nil

  /// Optional. The labels or tags associated with the Autonomous Database.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Immutable. The name of the VPC network used by the Autonomous
  /// Database in the following format:
  /// projects/{project}/global/networks/{network}
  public var network: Swift.String = Swift.String()

  /// Optional. Immutable. The subnet CIDR range for the Autonomous Database.
  public var cidr: Swift.String = Swift.String()

  /// Optional. Immutable. The name of the OdbNetwork associated with the
  /// Autonomous Database. Format:
  /// projects/{project}/locations/{location}/odbNetworks/{odb_network} It is
  /// optional but if specified, this should match the parent ODBNetwork of the
  /// OdbSubnet.
  public var odbNetwork: Swift.String = Swift.String()

  /// Optional. Immutable. The name of the OdbSubnet associated with the
  /// Autonomous Database. Format:
  /// projects/{project}/locations/{location}/odbNetworks/{odb_network}/odbSubnets/{odb_subnet}
  public var odbSubnet: Swift.String = Swift.String()

  /// Optional. Immutable. The source Autonomous Database configuration for the
  /// standby Autonomous Database. The source Autonomous Database is configured
  /// while creating the Peer Autonomous Database and can't be updated after
  /// creation.
  public var sourceConfig: SourceConfig? = nil

  /// Output only. The peer Autonomous Database names of the given Autonomous
  /// Database.
  public var peerAutonomousDatabases: [Swift.String] = []

  /// Output only. The date and time that the Autonomous Database was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. List of supported GCP region to clone the Autonomous Database
  /// for disaster recovery. Format: `project/{project}/locations/{location}`.
  public var disasterRecoverySupportedLocations: [Swift.String] = []

  /// Initialize a new instance of `AutonomousDatabase`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutonomousDatabase().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.AutonomousDatabase"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
