// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The URLs for accessing Oracle Application Express (APEX) and SQL Developer
/// Web with a browser from a Compute instance.
/// https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/datatypes/AutonomousDatabaseConnectionUrls
public struct AutonomousDatabaseConnectionUrls: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Oracle Application Express (APEX) URL.
  public var apexUri: Swift.String = Swift.String()

  /// Output only. The URL of the Database Transforms for the Autonomous
  /// Database.
  public var databaseTransformsUri: Swift.String = Swift.String()

  /// Output only. The URL of the Graph Studio for the Autonomous Database.
  public var graphStudioUri: Swift.String = Swift.String()

  /// Output only. The URL of the Oracle Machine Learning (OML) Notebook for the
  /// Autonomous Database.
  public var machineLearningNotebookUri: Swift.String = Swift.String()

  /// Output only. The URL of Machine Learning user management the Autonomous
  /// Database.
  public var machineLearningUserManagementUri: Swift.String = Swift.String()

  /// Output only. The URL of the MongoDB API for the Autonomous Database.
  public var mongoDbUri: Swift.String = Swift.String()

  /// Output only. The Oracle REST Data Services (ORDS) URL of the Web Access for
  /// the Autonomous Database.
  public var ordsUri: Swift.String = Swift.String()

  /// Output only. The URL of the Oracle SQL Developer Web for the Autonomous
  /// Database.
  public var sqlDevWebUri: Swift.String = Swift.String()

  /// Initialize a new instance of `AutonomousDatabaseConnectionUrls`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutonomousDatabaseConnectionUrls().with { $0.apexUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.AutonomousDatabaseConnectionUrls"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
