// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The properties of an Autonomous Database.
public struct AutonomousDatabaseProperties: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. OCID of the Autonomous Database.
  /// https://docs.oracle.com/en-us/iaas/Content/General/Concepts/identifiers.htm#Oracle
  public var ocid: Swift.String = Swift.String()

  /// Optional. Immutable. The number of compute servers for the Autonomous
  /// Database.
  public var computeCount: Swift.Float = Swift.Float()

  /// Optional. Immutable. The number of CPU cores to be made available to the
  /// database.
  public var cpuCoreCount: Swift.Int32 = Swift.Int32()

  /// Optional. Immutable. The size of the data stored in the database, in
  /// terabytes.
  public var dataStorageSizeTb: Swift.Int32 = Swift.Int32()

  /// Optional. Immutable. The size of the data stored in the database, in
  /// gigabytes.
  public var dataStorageSizeGb: Swift.Int32 = Swift.Int32()

  /// Required. Immutable. The workload type of the Autonomous Database.
  public var dbWorkload: DBWorkload = DBWorkload()

  /// Optional. Immutable. The edition of the Autonomous Databases.
  public var dbEdition: AutonomousDatabaseProperties.DatabaseEdition =
    AutonomousDatabaseProperties.DatabaseEdition()

  /// Optional. Immutable. The character set for the Autonomous Database. The
  /// default is AL32UTF8.
  public var characterSet: Swift.String = Swift.String()

  /// Optional. Immutable. The national character set for the Autonomous
  /// Database. The default is AL16UTF16.
  public var nCharacterSet: Swift.String = Swift.String()

  /// Optional. Immutable. The private endpoint IP address for the Autonomous
  /// Database.
  public var privateEndpointIp: Swift.String = Swift.String()

  /// Optional. Immutable. The private endpoint label for the Autonomous
  /// Database.
  public var privateEndpointLabel: Swift.String = Swift.String()

  /// Optional. Immutable. The Oracle Database version for the Autonomous
  /// Database.
  public var dbVersion: Swift.String = Swift.String()

  /// Optional. Immutable. This field indicates if auto scaling is enabled for
  /// the Autonomous Database CPU core count.
  public var isAutoScalingEnabled: Swift.Bool = Swift.Bool()

  /// Optional. Immutable. This field indicates if auto scaling is enabled for
  /// the Autonomous Database storage.
  public var isStorageAutoScalingEnabled: Swift.Bool = Swift.Bool()

  /// Required. Immutable. The license type used for the Autonomous Database.
  public var licenseType: AutonomousDatabaseProperties.LicenseType =
    AutonomousDatabaseProperties.LicenseType()

  /// Optional. Immutable. The list of customer contacts.
  public var customerContacts: [CustomerContact] = []

  /// Optional. Immutable. The ID of the Oracle Cloud Infrastructure vault
  /// secret.
  public var secretId: Swift.String = Swift.String()

  /// Optional. Immutable. The ID of the Oracle Cloud Infrastructure vault.
  public var vaultId: Swift.String = Swift.String()

  /// Optional. Immutable. The maintenance schedule of the Autonomous Database.
  public var maintenanceScheduleType: AutonomousDatabaseProperties.MaintenanceScheduleType =
    AutonomousDatabaseProperties.MaintenanceScheduleType()

  /// Optional. Immutable. This field specifies if the Autonomous Database
  /// requires mTLS connections.
  public var mtlsConnectionRequired: Swift.Bool = Swift.Bool()

  /// Optional. Immutable. The retention period for the Autonomous Database. This
  /// field is specified in days, can range from 1 day to 60 days, and has a
  /// default value of 60 days.
  public var backupRetentionPeriodDays: Swift.Int32 = Swift.Int32()

  /// Output only. The amount of storage currently being used for user and system
  /// data, in terabytes.
  public var actualUsedDataStorageSizeTb: Swift.Double = Swift.Double()

  /// Output only. The amount of storage currently allocated for the database
  /// tables and billed for, rounded up in terabytes.
  public var allocatedStorageSizeTb: Swift.Double = Swift.Double()

  /// Output only. The details for the Oracle APEX Application Development.
  public var apexDetails: AutonomousDatabaseApex? = nil

  /// Output only. This field indicates the status of Data Guard and Access
  /// control for the Autonomous Database. The field's value is null if Data
  /// Guard is disabled or Access Control is disabled. The field's value is TRUE
  /// if both Data Guard and Access Control are enabled, and the Autonomous
  /// Database is using primary IP access control list (ACL) for standby. The
  /// field's value is FALSE if both Data Guard and Access Control are enabled,
  /// and the Autonomous Database is using a different IP access control list
  /// (ACL) for standby compared to primary.
  public var arePrimaryAllowlistedIpsUsed: Swift.Bool? = nil

  /// Output only. The details of the current lifestyle state of the Autonomous
  /// Database.
  public var lifecycleDetails: Swift.String = Swift.String()

  /// Output only. The current lifecycle state of the Autonomous Database.
  public var state: State = State()

  /// Output only. The Autonomous Container Database OCID.
  public var autonomousContainerDatabaseId: Swift.String = Swift.String()

  /// Output only. The list of available Oracle Database upgrade versions for an
  /// Autonomous Database.
  public var availableUpgradeVersions: [Swift.String] = []

  /// Output only. The connection strings used to connect to an Autonomous
  /// Database.
  public var connectionStrings: AutonomousDatabaseConnectionStrings? = nil

  /// Output only. The Oracle Connection URLs for an Autonomous Database.
  public var connectionUrls: AutonomousDatabaseConnectionUrls? = nil

  /// Output only. This field indicates the number of seconds of data loss during
  /// a Data Guard failover.
  public var failedDataRecoveryDuration: GoogleCloudWkt.Duration? = nil

  /// Output only. The memory assigned to in-memory tables in an Autonomous
  /// Database.
  public var memoryTableGbs: Swift.Int32 = Swift.Int32()

  /// Output only. Deprecated: Please use `local_data_guard_enabled` instead.
  /// This field indicates whether the Autonomous Database has local (in-region)
  /// Data Guard enabled.
  @available(*, deprecated)
  public var isLocalDataGuardEnabled: Swift.Bool = Swift.Bool()

  /// Output only. Deprecated: Please use
  /// `local_adg_auto_failover_max_data_loss_limit_duration` instead.
  /// This field indicates the maximum data loss limit for an Autonomous
  /// Database, in seconds.
  @available(*, deprecated)
  public var localAdgAutoFailoverMaxDataLossLimit: Swift.Int32 = Swift.Int32()

  /// Output only. The details of the Autonomous Data Guard standby database.
  public var localStandbyDb: AutonomousDatabaseStandbySummary? = nil

  /// Output only. The amount of memory enabled per ECPU, in gigabytes.
  public var memoryPerOracleComputeUnitGbs: Swift.Int32 = Swift.Int32()

  /// Output only. This field indicates the local disaster recovery (DR) type of
  /// an Autonomous Database.
  public var localDisasterRecoveryType: AutonomousDatabaseProperties.LocalDisasterRecoveryType =
    AutonomousDatabaseProperties.LocalDisasterRecoveryType()

  /// Output only. The current state of the Data Safe registration for the
  /// Autonomous Database.
  public var dataSafeState: AutonomousDatabaseProperties.DataSafeState =
    AutonomousDatabaseProperties.DataSafeState()

  /// Output only. The current state of database management for the Autonomous
  /// Database.
  public var databaseManagementState: AutonomousDatabaseProperties.DatabaseManagementState =
    AutonomousDatabaseProperties.DatabaseManagementState()

  /// Output only. This field indicates the current mode of the Autonomous
  /// Database.
  public var openMode: AutonomousDatabaseProperties.OpenMode =
    AutonomousDatabaseProperties.OpenMode()

  /// Output only. This field indicates the state of Operations Insights for the
  /// Autonomous Database.
  public var operationsInsightsState: OperationsInsightsState = OperationsInsightsState()

  /// Output only. The list of OCIDs of standby databases located in Autonomous
  /// Data Guard remote regions that are associated with the source database.
  public var peerDbIds: [Swift.String] = []

  /// Output only. The permission level of the Autonomous Database.
  public var permissionLevel: AutonomousDatabaseProperties.PermissionLevel =
    AutonomousDatabaseProperties.PermissionLevel()

  /// Output only. The private endpoint for the Autonomous Database.
  public var privateEndpoint: Swift.String = Swift.String()

  /// Output only. The refresh mode of the cloned Autonomous Database.
  public var refreshableMode: AutonomousDatabaseProperties.RefreshableMode =
    AutonomousDatabaseProperties.RefreshableMode()

  /// Output only. The refresh State of the clone.
  public var refreshableState: AutonomousDatabaseProperties.RefreshableState =
    AutonomousDatabaseProperties.RefreshableState()

  /// Output only. The Data Guard role of the Autonomous Database.
  public var role: AutonomousDatabaseProperties.Role = AutonomousDatabaseProperties.Role()

  /// Output only. The list and details of the scheduled operations of the
  /// Autonomous Database.
  public var scheduledOperationDetails: [ScheduledOperationDetails] = []

  /// Output only. The SQL Web Developer URL for the Autonomous Database.
  public var sqlWebDeveloperUrl: Swift.String = Swift.String()

  /// Output only. The list of available regions that can be used to create a
  /// clone for the Autonomous Database.
  public var supportedCloneRegions: [Swift.String] = []

  /// Output only. The storage space used by Autonomous Database, in gigabytes.
  public var usedDataStorageSizeTbs: Swift.Int32 = Swift.Int32()

  /// Output only. The Oracle Cloud Infrastructure link for the Autonomous
  /// Database.
  public var ociUrl: Swift.String = Swift.String()

  /// Output only. The storage space used by automatic backups of Autonomous
  /// Database, in gigabytes.
  public var totalAutoBackupStorageSizeGbs: Swift.Float = Swift.Float()

  /// Output only. The long term backup schedule of the Autonomous Database.
  public var nextLongTermBackupTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The date and time the Autonomous Data Guard role was changed
  /// for the standby Autonomous Database.
  public var dataGuardRoleChangedTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The date and time the Disaster Recovery role was changed for
  /// the standby Autonomous Database.
  public var disasterRecoveryRoleChangedTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The date and time when maintenance will begin.
  public var maintenanceBeginTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The date and time when maintenance will end.
  public var maintenanceEndTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Immutable. The list of allowlisted IP addresses for the
  /// Autonomous Database.
  public var allowlistedIps: [Swift.String] = []

  /// Optional. The encryption key used to encrypt the Autonomous Database.
  /// Updating this field will add a new entry in the
  /// `encryption_key_history_entries` field with the former version.
  public var encryptionKey: EncryptionKey? = nil

  /// Output only. The history of the encryption keys used to encrypt the
  /// Autonomous Database.
  public var encryptionKeyHistoryEntries: [EncryptionKeyHistoryEntry] = []

  /// Output only. An Oracle-managed Google Cloud service account on which
  /// customers can grant roles to access resources in the customer project.
  public var serviceAgentEmail: Swift.String = Swift.String()

  /// Optional. Indicates whether the Autonomous Database has a local (in-region)
  /// standby database. Not applicable to cross-region Data Guard or dedicated
  /// Exadata infrastructure.
  public var localDataGuardEnabled: Swift.Bool? = nil

  /// Optional. This field indicates the maximum data loss limit for an
  /// Autonomous Database, in seconds.
  public var localAdgAutoFailoverMaxDataLossLimitDuration: Swift.Int32? = nil

  /// Optional. Indicates if the Autonomous Database is a refreshable clone. This
  /// field is used in update flow to connect / disconnect a refreshable clone
  /// from its source database.
  public var refreshableClone: Swift.Bool? = nil

  /// Initialize a new instance of `AutonomousDatabaseProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutonomousDatabaseProperties().with { $0.ocid = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The editions available for the Autonomous Database.
  public enum DatabaseEdition: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Standard Database Edition
    case standardEdition
    /// Enterprise Database Edition
    case enterpriseEdition
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .standardEdition: return 1
      case .enterpriseEdition: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DATABASE_EDITION_UNSPECIFIED"
      case .standardEdition: return "STANDARD_EDITION"
      case .enterpriseEdition: return "ENTERPRISE_EDITION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DatabaseEdition/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DATABASE_EDITION_UNSPECIFIED": self = .unspecified
      case "STANDARD_EDITION": self = .standardEdition
      case "ENTERPRISE_EDITION": self = .enterpriseEdition
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DatabaseEdition/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .standardEdition
      case 2: self = .enterpriseEdition
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .standardEdition: return try container.encode(1)
      case .enterpriseEdition: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The license types available for the Autonomous Database.
  public enum LicenseType: Codable, Equatable, Sendable {
    /// Unspecified
    case unspecified
    /// License included part of offer
    case licenseIncluded
    /// Bring your own license
    case bringYourOwnLicense
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .licenseIncluded: return 1
      case .bringYourOwnLicense: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "LICENSE_TYPE_UNSPECIFIED"
      case .licenseIncluded: return "LICENSE_INCLUDED"
      case .bringYourOwnLicense: return "BRING_YOUR_OWN_LICENSE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LicenseType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "LICENSE_TYPE_UNSPECIFIED": self = .unspecified
      case "LICENSE_INCLUDED": self = .licenseIncluded
      case "BRING_YOUR_OWN_LICENSE": self = .bringYourOwnLicense
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LicenseType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .licenseIncluded
      case 2: self = .bringYourOwnLicense
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .licenseIncluded: return try container.encode(1)
      case .bringYourOwnLicense: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The available maintenance schedules for the Autonomous Database.
  public enum MaintenanceScheduleType: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// An EARLY maintenance schedule patches the database before
    /// the regular scheduled maintenance.
    case early
    /// A REGULAR maintenance schedule follows the normal maintenance cycle.
    case regular
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .early: return 1
      case .regular: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MAINTENANCE_SCHEDULE_TYPE_UNSPECIFIED"
      case .early: return "EARLY"
      case .regular: return "REGULAR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:MaintenanceScheduleType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MAINTENANCE_SCHEDULE_TYPE_UNSPECIFIED": self = .unspecified
      case "EARLY": self = .early
      case "REGULAR": self = .regular
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:MaintenanceScheduleType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .early
      case 2: self = .regular
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .early: return try container.encode(1)
      case .regular: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The types of local disaster recovery available for an Autonomous Database.
  public enum LocalDisasterRecoveryType: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Autonomous Data Guard recovery.
    case adg
    /// Backup based recovery.
    case backupBased
    /// Local disaster recovery is not available.
    case notAvailable
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .adg: return 1
      case .backupBased: return 2
      case .notAvailable: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "LOCAL_DISASTER_RECOVERY_TYPE_UNSPECIFIED"
      case .adg: return "ADG"
      case .backupBased: return "BACKUP_BASED"
      case .notAvailable: return "NOT_AVAILABLE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LocalDisasterRecoveryType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "LOCAL_DISASTER_RECOVERY_TYPE_UNSPECIFIED": self = .unspecified
      case "ADG": self = .adg
      case "BACKUP_BASED": self = .backupBased
      case "NOT_AVAILABLE": self = .notAvailable
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LocalDisasterRecoveryType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .adg
      case 2: self = .backupBased
      case 3: self = .notAvailable
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .adg: return try container.encode(1)
      case .backupBased: return try container.encode(2)
      case .notAvailable: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Varies states of the Data Safe registration for the Autonomous Database.
  public enum DataSafeState: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Registering data safe state.
    case registering
    /// Registered data safe state.
    case registered
    /// Deregistering data safe state.
    case deregistering
    /// Not registered data safe state.
    case notRegistered
    /// Failed data safe state.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .registering: return 1
      case .registered: return 2
      case .deregistering: return 3
      case .notRegistered: return 4
      case .failed: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DATA_SAFE_STATE_UNSPECIFIED"
      case .registering: return "REGISTERING"
      case .registered: return "REGISTERED"
      case .deregistering: return "DEREGISTERING"
      case .notRegistered: return "NOT_REGISTERED"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DataSafeState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DATA_SAFE_STATE_UNSPECIFIED": self = .unspecified
      case "REGISTERING": self = .registering
      case "REGISTERED": self = .registered
      case "DEREGISTERING": self = .deregistering
      case "NOT_REGISTERED": self = .notRegistered
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DataSafeState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .registering
      case 2: self = .registered
      case 3: self = .deregistering
      case 4: self = .notRegistered
      case 5: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .registering: return try container.encode(1)
      case .registered: return try container.encode(2)
      case .deregistering: return try container.encode(3)
      case .notRegistered: return try container.encode(4)
      case .failed: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The different states of database management for an Autonomous Database.
  public enum DatabaseManagementState: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Enabling Database Management state
    case enabling
    /// Enabled Database Management state
    case enabled
    /// Disabling Database Management state
    case disabling
    /// Not Enabled Database Management state
    case notEnabled
    /// Failed enabling Database Management state
    case failedEnabling
    /// Failed disabling Database Management state
    case failedDisabling
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .enabling: return 1
      case .enabled: return 2
      case .disabling: return 3
      case .notEnabled: return 4
      case .failedEnabling: return 5
      case .failedDisabling: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DATABASE_MANAGEMENT_STATE_UNSPECIFIED"
      case .enabling: return "ENABLING"
      case .enabled: return "ENABLED"
      case .disabling: return "DISABLING"
      case .notEnabled: return "NOT_ENABLED"
      case .failedEnabling: return "FAILED_ENABLING"
      case .failedDisabling: return "FAILED_DISABLING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DatabaseManagementState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DATABASE_MANAGEMENT_STATE_UNSPECIFIED": self = .unspecified
      case "ENABLING": self = .enabling
      case "ENABLED": self = .enabled
      case "DISABLING": self = .disabling
      case "NOT_ENABLED": self = .notEnabled
      case "FAILED_ENABLING": self = .failedEnabling
      case "FAILED_DISABLING": self = .failedDisabling
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DatabaseManagementState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .enabling
      case 2: self = .enabled
      case 3: self = .disabling
      case 4: self = .notEnabled
      case 5: self = .failedEnabling
      case 6: self = .failedDisabling
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .enabling: return try container.encode(1)
      case .enabled: return try container.encode(2)
      case .disabling: return try container.encode(3)
      case .notEnabled: return try container.encode(4)
      case .failedEnabling: return try container.encode(5)
      case .failedDisabling: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// This field indicates the modes of an Autonomous Database.
  public enum OpenMode: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Read Only Mode
    case readOnly
    /// Read Write Mode
    case readWrite
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .readOnly: return 1
      case .readWrite: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "OPEN_MODE_UNSPECIFIED"
      case .readOnly: return "READ_ONLY"
      case .readWrite: return "READ_WRITE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OpenMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "OPEN_MODE_UNSPECIFIED": self = .unspecified
      case "READ_ONLY": self = .readOnly
      case "READ_WRITE": self = .readWrite
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OpenMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .readOnly
      case 2: self = .readWrite
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .readOnly: return try container.encode(1)
      case .readWrite: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The types of permission levels for an Autonomous Database.
  public enum PermissionLevel: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Restricted mode allows access only by admin users.
    case restricted
    /// Normal access.
    case unrestricted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .restricted: return 1
      case .unrestricted: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PERMISSION_LEVEL_UNSPECIFIED"
      case .restricted: return "RESTRICTED"
      case .unrestricted: return "UNRESTRICTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PermissionLevel/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PERMISSION_LEVEL_UNSPECIFIED": self = .unspecified
      case "RESTRICTED": self = .restricted
      case "UNRESTRICTED": self = .unrestricted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PermissionLevel/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .restricted
      case 2: self = .unrestricted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .restricted: return try container.encode(1)
      case .unrestricted: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The refresh mode of the cloned Autonomous Database.
  public enum RefreshableMode: Codable, Equatable, Sendable {
    /// The default unspecified value.
    case unspecified
    /// AUTOMATIC indicates that the cloned database is automatically
    /// refreshed with data from the source Autonomous Database.
    case automatic
    /// MANUAL indicates that the cloned database is manually refreshed with
    /// data from the source Autonomous Database.
    case manual
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .automatic: return 1
      case .manual: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "REFRESHABLE_MODE_UNSPECIFIED"
      case .automatic: return "AUTOMATIC"
      case .manual: return "MANUAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RefreshableMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "REFRESHABLE_MODE_UNSPECIFIED": self = .unspecified
      case "AUTOMATIC": self = .automatic
      case "MANUAL": self = .manual
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RefreshableMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .automatic
      case 2: self = .manual
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .automatic: return try container.encode(1)
      case .manual: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The refresh state of the cloned Autonomous Database.
  public enum RefreshableState: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Refreshing
    case refreshing
    /// Not refreshed
    case notRefreshing
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .refreshing: return 1
      case .notRefreshing: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "REFRESHABLE_STATE_UNSPECIFIED"
      case .refreshing: return "REFRESHING"
      case .notRefreshing: return "NOT_REFRESHING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RefreshableState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "REFRESHABLE_STATE_UNSPECIFIED": self = .unspecified
      case "REFRESHING": self = .refreshing
      case "NOT_REFRESHING": self = .notRefreshing
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RefreshableState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .refreshing
      case 2: self = .notRefreshing
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .refreshing: return try container.encode(1)
      case .notRefreshing: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The Data Guard role of the Autonomous Database.
  public enum Role: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Primary role
    case primary
    /// Standby role
    case standby
    /// Disabled standby role
    case disabledStandby
    /// Backup copy role
    case backupCopy
    /// Snapshot standby role
    case snapshotStandby
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .primary: return 1
      case .standby: return 2
      case .disabledStandby: return 3
      case .backupCopy: return 4
      case .snapshotStandby: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ROLE_UNSPECIFIED"
      case .primary: return "PRIMARY"
      case .standby: return "STANDBY"
      case .disabledStandby: return "DISABLED_STANDBY"
      case .backupCopy: return "BACKUP_COPY"
      case .snapshotStandby: return "SNAPSHOT_STANDBY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Role/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ROLE_UNSPECIFIED": self = .unspecified
      case "PRIMARY": self = .primary
      case "STANDBY": self = .standby
      case "DISABLED_STANDBY": self = .disabledStandby
      case "BACKUP_COPY": self = .backupCopy
      case "SNAPSHOT_STANDBY": self = .snapshotStandby
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Role/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .primary
      case 2: self = .standby
      case 3: self = .disabledStandby
      case 4: self = .backupCopy
      case 5: self = .snapshotStandby
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .primary: return try container.encode(1)
      case .standby: return try container.encode(2)
      case .disabledStandby: return try container.encode(3)
      case .backupCopy: return try container.encode(4)
      case .snapshotStandby: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.AutonomousDatabaseProperties"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
