// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The configuration of the Database Management service.
public struct DatabaseManagementConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The status of the Database Management service.
  public var managementState: DatabaseManagementConfig.ManagementState =
    DatabaseManagementConfig.ManagementState()

  /// Output only. The Database Management type.
  public var managementType: DatabaseManagementConfig.ManagementType =
    DatabaseManagementConfig.ManagementType()

  /// Initialize a new instance of `DatabaseManagementConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DatabaseManagementConfig().with { $0.managementState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The status of the Database Management service.
  public enum ManagementState: Codable, Equatable, Sendable {
    /// The status is not specified.
    case unspecified
    /// The Database Management service is enabling.
    case enabling
    /// The Database Management service is enabled.
    case enabled
    /// The Database Management service is disabling.
    case disabling
    /// The Database Management service is disabled.
    case disabled
    /// The Database Management service is updating.
    case updating
    /// The Database Management service failed to enable.
    case failedEnabling
    /// The Database Management service failed to disable.
    case failedDisabling
    /// The Database Management service failed to update.
    case failedUpdating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .enabling: return 1
      case .enabled: return 2
      case .disabling: return 3
      case .disabled: return 4
      case .updating: return 5
      case .failedEnabling: return 6
      case .failedDisabling: return 7
      case .failedUpdating: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MANAGEMENT_STATE_UNSPECIFIED"
      case .enabling: return "ENABLING"
      case .enabled: return "ENABLED"
      case .disabling: return "DISABLING"
      case .disabled: return "DISABLED"
      case .updating: return "UPDATING"
      case .failedEnabling: return "FAILED_ENABLING"
      case .failedDisabling: return "FAILED_DISABLING"
      case .failedUpdating: return "FAILED_UPDATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ManagementState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MANAGEMENT_STATE_UNSPECIFIED": self = .unspecified
      case "ENABLING": self = .enabling
      case "ENABLED": self = .enabled
      case "DISABLING": self = .disabling
      case "DISABLED": self = .disabled
      case "UPDATING": self = .updating
      case "FAILED_ENABLING": self = .failedEnabling
      case "FAILED_DISABLING": self = .failedDisabling
      case "FAILED_UPDATING": self = .failedUpdating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ManagementState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .enabling
      case 2: self = .enabled
      case 3: self = .disabling
      case 4: self = .disabled
      case 5: self = .updating
      case 6: self = .failedEnabling
      case 7: self = .failedDisabling
      case 8: self = .failedUpdating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .enabling: return try container.encode(1)
      case .enabled: return try container.encode(2)
      case .disabling: return try container.encode(3)
      case .disabled: return try container.encode(4)
      case .updating: return try container.encode(5)
      case .failedEnabling: return try container.encode(6)
      case .failedDisabling: return try container.encode(7)
      case .failedUpdating: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The Database Management type.
  public enum ManagementType: Codable, Equatable, Sendable {
    /// The type is not specified.
    case unspecified
    /// Basic Database Management.
    case basic
    /// Advanced Database Management.
    case advanced
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .basic: return 1
      case .advanced: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MANAGEMENT_TYPE_UNSPECIFIED"
      case .basic: return "BASIC"
      case .advanced: return "ADVANCED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ManagementType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MANAGEMENT_TYPE_UNSPECIFIED": self = .unspecified
      case "BASIC": self = .basic
      case "ADVANCED": self = .advanced
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ManagementType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .basic
      case 2: self = .advanced
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .basic: return try container.encode(1)
      case .advanced: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.DatabaseManagementConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
