// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Details of the Database resource.
/// https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/Database/
public struct Database: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The name of the Database resource in the following format:
  /// projects/{project}/locations/{region}/databases/{database}
  public var name: Swift.String = Swift.String()

  /// Optional. The database name. The name must begin with an alphabetic
  /// character and can contain a maximum of eight alphanumeric characters.
  /// Special characters are not permitted.
  public var dbName: Swift.String = Swift.String()

  /// Optional. The DB_UNIQUE_NAME of the Oracle Database being backed up.
  public var dbUniqueName: Swift.String = Swift.String()

  /// Optional. The password for the default ADMIN user.
  /// Note: Only one of `admin_password_secret_version` or `admin_password` can
  /// be populated.
  public var adminPassword: Swift.String = Swift.String()

  /// Optional. The resource name of a secret version in Secret Manager which
  /// contains the database admin user's password. Format:
  /// projects/{project}/secrets/{secret}/versions/{version}. Note: Only one of
  /// `admin_password_secret_version` or `admin_password` can be populated.
  public var adminPasswordSecretVersion: Swift.String = Swift.String()

  /// Optional. The TDE wallet password for the database.
  /// Note: Only one of `tde_wallet_password_secret_version` or
  /// `tde_wallet_password` can be populated.
  public var tdeWalletPassword: Swift.String = Swift.String()

  /// Optional. The resource name of a secret version in Secret Manager which
  /// contains the TDE wallet password for the database. Format:
  /// projects/{project}/secrets/{secret}/versions/{version}. Note: Only one of
  /// `tde_wallet_password_secret_version` or `tde_wallet_password` can be
  /// populated.
  public var tdeWalletPasswordSecretVersion: Swift.String = Swift.String()

  /// Optional. The character set for the database. The default is AL32UTF8.
  public var characterSet: Swift.String = Swift.String()

  /// Optional. The national character set for the database. The default is
  /// AL16UTF16.
  public var ncharacterSet: Swift.String = Swift.String()

  /// Output only. HTTPS link to OCI resources exposed to Customer via UI
  /// Interface.
  public var ociUrl: Swift.String = Swift.String()

  /// Output only. The date and time that the Database was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. The properties of the Database.
  public var properties: DatabaseProperties? = nil

  /// Optional. The database ID of the Database.
  public var databaseId: Swift.String = Swift.String()

  /// Optional. The name of the DbHome resource associated with the Database.
  public var dbHomeName: Swift.String = Swift.String()

  /// Output only. The GCP Oracle zone where the Database is created.
  public var gcpOracleZone: Swift.String = Swift.String()

  /// Output only. The Status of Operations Insights for this Database.
  public var opsInsightsStatus: Database.OperationsInsightsStatus =
    Database.OperationsInsightsStatus()

  /// Optional. The ID of the pluggable database associated with the Database.
  /// The ID must be unique within the project and location.
  public var pluggableDatabaseId: Swift.String = Swift.String()

  /// Optional. The pluggable database associated with the Database. The name
  /// must begin with an alphabetic character and can contain a maximum of thirty
  /// alphanumeric characters.
  public var pluggableDatabaseName: Swift.String = Swift.String()

  /// Initialize a new instance of `Database`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Database().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The Status of Operations Insights for this Database.
  public enum OperationsInsightsStatus: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Indicates that the operations insights are being enabled.
    case enabling
    /// Indicates that the operations insights are enabled.
    case enabled
    /// Indicates that the operations insights are being disabled.
    case disabling
    /// Indicates that the operations insights are not enabled.
    case notEnabled
    /// Indicates that the operations insights failed to enable.
    case failedEnabling
    /// Indicates that the operations insights failed to disable.
    case failedDisabling
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .enabling: return 1
      case .enabled: return 2
      case .disabling: return 3
      case .notEnabled: return 4
      case .failedEnabling: return 5
      case .failedDisabling: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "OPERATIONS_INSIGHTS_STATUS_UNSPECIFIED"
      case .enabling: return "ENABLING"
      case .enabled: return "ENABLED"
      case .disabling: return "DISABLING"
      case .notEnabled: return "NOT_ENABLED"
      case .failedEnabling: return "FAILED_ENABLING"
      case .failedDisabling: return "FAILED_DISABLING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OperationsInsightsStatus/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "OPERATIONS_INSIGHTS_STATUS_UNSPECIFIED": self = .unspecified
      case "ENABLING": self = .enabling
      case "ENABLED": self = .enabled
      case "DISABLING": self = .disabling
      case "NOT_ENABLED": self = .notEnabled
      case "FAILED_ENABLING": self = .failedEnabling
      case "FAILED_DISABLING": self = .failedDisabling
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OperationsInsightsStatus/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .enabling
      case 2: self = .enabled
      case 3: self = .disabling
      case 4: self = .notEnabled
      case 5: self = .failedEnabling
      case 6: self = .failedDisabling
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .enabling: return try container.encode(1)
      case .enabled: return try container.encode(2)
      case .disabling: return try container.encode(3)
      case .notEnabled: return try container.encode(4)
      case .failedEnabling: return try container.encode(5)
      case .failedDisabling: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.Database"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
