// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The connection string profile to allow clients to group.
/// https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/datatypes/DatabaseConnectionStringProfile
public struct DatabaseConnectionStringProfile: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The current consumer group being used by the connection.
  public var consumerGroup: DatabaseConnectionStringProfile.ConsumerGroup =
    DatabaseConnectionStringProfile.ConsumerGroup()

  /// Output only. The display name for the database connection.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The host name format being currently used in connection
  /// string.
  public var hostFormat: DatabaseConnectionStringProfile.HostFormat =
    DatabaseConnectionStringProfile.HostFormat()

  /// Output only. This field indicates if the connection string is regional and
  /// is only applicable for cross-region Data Guard.
  public var isRegional: Swift.Bool = Swift.Bool()

  /// Output only. The protocol being used by the connection.
  public var `protocol`: DatabaseConnectionStringProfile.Protocol_ =
    DatabaseConnectionStringProfile.Protocol_()

  /// Output only. The current session mode of the connection.
  public var sessionMode: DatabaseConnectionStringProfile.SessionMode =
    DatabaseConnectionStringProfile.SessionMode()

  /// Output only. The syntax of the connection string.
  public var syntaxFormat: DatabaseConnectionStringProfile.SyntaxFormat =
    DatabaseConnectionStringProfile.SyntaxFormat()

  /// Output only. This field indicates the TLS authentication type of the
  /// connection.
  public var tlsAuthentication: DatabaseConnectionStringProfile.TLSAuthentication =
    DatabaseConnectionStringProfile.TLSAuthentication()

  /// Output only. The value of the connection string.
  public var value: Swift.String = Swift.String()

  /// Initialize a new instance of `DatabaseConnectionStringProfile`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DatabaseConnectionStringProfile().with { $0.consumerGroup = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case consumerGroup = "consumerGroup"
    case displayName = "displayName"
    case hostFormat = "hostFormat"
    case isRegional = "isRegional"
    case `protocol` = "protocol"
    case sessionMode = "sessionMode"
    case syntaxFormat = "syntaxFormat"
    case tlsAuthentication = "tlsAuthentication"
    case value = "value"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.consumerGroup = try container.decode(
      DatabaseConnectionStringProfile.ConsumerGroup.self, forKey: .consumerGroup)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.hostFormat = try container.decode(
      DatabaseConnectionStringProfile.HostFormat.self, forKey: .hostFormat)
    self.isRegional = try container.decode(Swift.Bool.self, forKey: .isRegional)
    self.`protocol` = try container.decode(
      DatabaseConnectionStringProfile.Protocol_.self, forKey: .`protocol`)
    self.sessionMode = try container.decode(
      DatabaseConnectionStringProfile.SessionMode.self, forKey: .sessionMode)
    self.syntaxFormat = try container.decode(
      DatabaseConnectionStringProfile.SyntaxFormat.self, forKey: .syntaxFormat)
    self.tlsAuthentication = try container.decode(
      DatabaseConnectionStringProfile.TLSAuthentication.self, forKey: .tlsAuthentication)
    self.value = try container.decode(Swift.String.self, forKey: .value)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.consumerGroup, forKey: .consumerGroup)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.hostFormat, forKey: .hostFormat)
    try container.encode(self.isRegional, forKey: .isRegional)
    try container.encode(self.`protocol`, forKey: .`protocol`)
    try container.encode(self.sessionMode, forKey: .sessionMode)
    try container.encode(self.syntaxFormat, forKey: .syntaxFormat)
    try container.encode(self.tlsAuthentication, forKey: .tlsAuthentication)
    try container.encode(self.value, forKey: .value)
  }

  /// The various consumer groups available in the connection string profile.
  public enum ConsumerGroup: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// High consumer group.
    case high
    /// Medium consumer group.
    case medium
    /// Low consumer group.
    case low
    /// TP consumer group.
    case tp
    /// TPURGENT consumer group.
    case tpurgent
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .high: return 1
      case .medium: return 2
      case .low: return 3
      case .tp: return 4
      case .tpurgent: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CONSUMER_GROUP_UNSPECIFIED"
      case .high: return "HIGH"
      case .medium: return "MEDIUM"
      case .low: return "LOW"
      case .tp: return "TP"
      case .tpurgent: return "TPURGENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConsumerGroup/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CONSUMER_GROUP_UNSPECIFIED": self = .unspecified
      case "HIGH": self = .high
      case "MEDIUM": self = .medium
      case "LOW": self = .low
      case "TP": self = .tp
      case "TPURGENT": self = .tpurgent
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConsumerGroup/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .high
      case 2: self = .medium
      case 3: self = .low
      case 4: self = .tp
      case 5: self = .tpurgent
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .high: return try container.encode(1)
      case .medium: return try container.encode(2)
      case .low: return try container.encode(3)
      case .tp: return try container.encode(4)
      case .tpurgent: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The host name format being used in the connection string.
  public enum HostFormat: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// FQDN
    case fqdn
    /// IP
    case ip
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .fqdn: return 1
      case .ip: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "HOST_FORMAT_UNSPECIFIED"
      case .fqdn: return "FQDN"
      case .ip: return "IP"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:HostFormat/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "HOST_FORMAT_UNSPECIFIED": self = .unspecified
      case "FQDN": self = .fqdn
      case "IP": self = .ip
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:HostFormat/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .fqdn
      case 2: self = .ip
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .fqdn: return try container.encode(1)
      case .ip: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The protocol being used by the connection.
  public enum Protocol_: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Tcp
    case tcp
    /// Tcps
    case tcps
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .tcp: return 1
      case .tcps: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PROTOCOL_UNSPECIFIED"
      case .tcp: return "TCP"
      case .tcps: return "TCPS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Protocol_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PROTOCOL_UNSPECIFIED": self = .unspecified
      case "TCP": self = .tcp
      case "TCPS": self = .tcps
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Protocol_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .tcp
      case 2: self = .tcps
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .tcp: return try container.encode(1)
      case .tcps: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The session mode of the connection.
  public enum SessionMode: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Direct
    case direct
    /// Indirect
    case `indirect`
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .direct: return 1
      case .`indirect`: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SESSION_MODE_UNSPECIFIED"
      case .direct: return "DIRECT"
      case .`indirect`: return "INDIRECT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SessionMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SESSION_MODE_UNSPECIFIED": self = .unspecified
      case "DIRECT": self = .direct
      case "INDIRECT": self = .`indirect`
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SessionMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .direct
      case 2: self = .`indirect`
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .direct: return try container.encode(1)
      case .`indirect`: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Specifies syntax of the connection string.
  public enum SyntaxFormat: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Long
    case long
    /// Ezconnect
    case ezconnect
    /// Ezconnectplus
    case ezconnectplus
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .long: return 1
      case .ezconnect: return 2
      case .ezconnectplus: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SYNTAX_FORMAT_UNSPECIFIED"
      case .long: return "LONG"
      case .ezconnect: return "EZCONNECT"
      case .ezconnectplus: return "EZCONNECTPLUS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SyntaxFormat/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SYNTAX_FORMAT_UNSPECIFIED": self = .unspecified
      case "LONG": self = .long
      case "EZCONNECT": self = .ezconnect
      case "EZCONNECTPLUS": self = .ezconnectplus
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SyntaxFormat/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .long
      case 2: self = .ezconnect
      case 3: self = .ezconnectplus
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .long: return try container.encode(1)
      case .ezconnect: return try container.encode(2)
      case .ezconnectplus: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// This field indicates the TLS authentication type of the connection.
  public enum TLSAuthentication: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Server
    case server
    /// Mutual
    case mutual
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .server: return 1
      case .mutual: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TLS_AUTHENTICATION_UNSPECIFIED"
      case .server: return "SERVER"
      case .mutual: return "MUTUAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TLSAuthentication/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TLS_AUTHENTICATION_UNSPECIFIED": self = .unspecified
      case "SERVER": self = .server
      case "MUTUAL": self = .mutual
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TLSAuthentication/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .server
      case 2: self = .mutual
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .server: return try container.encode(1)
      case .mutual: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.DatabaseConnectionStringProfile"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
