// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Various properties and settings associated with Exadata database server.
public struct DbServerProperties: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. OCID of database server.
  public var ocid: Swift.String = Swift.String()

  /// Optional. OCPU count per database.
  public var ocpuCount: Swift.Int32 = Swift.Int32()

  /// Optional. Maximum OCPU count per database.
  public var maxOcpuCount: Swift.Int32 = Swift.Int32()

  /// Optional. Memory allocated in GBs.
  public var memorySizeGb: Swift.Int32 = Swift.Int32()

  /// Optional. Maximum memory allocated in GBs.
  public var maxMemorySizeGb: Swift.Int32 = Swift.Int32()

  /// Optional. Local storage per VM.
  public var dbNodeStorageSizeGb: Swift.Int32 = Swift.Int32()

  /// Optional. Maximum local storage per VM.
  public var maxDbNodeStorageSizeGb: Swift.Int32 = Swift.Int32()

  /// Optional. Vm count per database.
  public var vmCount: Swift.Int32 = Swift.Int32()

  /// Output only. State of the database server.
  public var state: DbServerProperties.State = DbServerProperties.State()

  /// Output only. OCID of database nodes associated with the database server.
  public var dbNodeIds: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `DbServerProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DbServerProperties().with { $0.ocid = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let ocid = CodingKeys(stringValue: "ocid")
    static let ocpuCount = CodingKeys(stringValue: "ocpuCount")
    static let maxOcpuCount = CodingKeys(stringValue: "maxOcpuCount")
    static let memorySizeGb = CodingKeys(stringValue: "memorySizeGb")
    static let maxMemorySizeGb = CodingKeys(stringValue: "maxMemorySizeGb")
    static let dbNodeStorageSizeGb = CodingKeys(stringValue: "dbNodeStorageSizeGb")
    static let maxDbNodeStorageSizeGb = CodingKeys(stringValue: "maxDbNodeStorageSizeGb")
    static let vmCount = CodingKeys(stringValue: "vmCount")
    static let state = CodingKeys(stringValue: "state")
    static let dbNodeIds = CodingKeys(stringValue: "dbNodeIds")

    static let _knownKeys: Set<Swift.String> = [
      "ocid",
      "ocpuCount",
      "maxOcpuCount",
      "memorySizeGb",
      "maxMemorySizeGb",
      "dbNodeStorageSizeGb",
      "maxDbNodeStorageSizeGb",
      "vmCount",
      "state",
      "dbNodeIds",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ocid) {
      self.ocid = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .ocpuCount) {
      self.ocpuCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxOcpuCount) {
      self.maxOcpuCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .memorySizeGb) {
      self.memorySizeGb = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxMemorySizeGb) {
      self.maxMemorySizeGb = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .dbNodeStorageSizeGb) {
      self.dbNodeStorageSizeGb = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxDbNodeStorageSizeGb)
    {
      self.maxDbNodeStorageSizeGb = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .vmCount) {
      self.vmCount = value
    }
    if let value = try container.decodeIfPresent(DbServerProperties.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .dbNodeIds) {
      self.dbNodeIds = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.ocid, forKey: .ocid)
    try container.encode(self.ocpuCount, forKey: .ocpuCount)
    try container.encode(self.maxOcpuCount, forKey: .maxOcpuCount)
    try container.encode(self.memorySizeGb, forKey: .memorySizeGb)
    try container.encode(self.maxMemorySizeGb, forKey: .maxMemorySizeGb)
    try container.encode(self.dbNodeStorageSizeGb, forKey: .dbNodeStorageSizeGb)
    try container.encode(self.maxDbNodeStorageSizeGb, forKey: .maxDbNodeStorageSizeGb)
    try container.encode(self.vmCount, forKey: .vmCount)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.dbNodeIds, forKey: .dbNodeIds)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The various lifecycle states of the database server.
  public enum State: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Indicates that the resource is in creating state.
    case creating
    /// Indicates that the resource is in available state.
    case available
    /// Indicates that the resource is in unavailable state.
    case unavailable
    /// Indicates that the resource is in deleting state.
    case deleting
    /// Indicates that the resource is in deleted state.
    case deleted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .available: return 2
      case .unavailable: return 3
      case .deleting: return 4
      case .deleted: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .available: return "AVAILABLE"
      case .unavailable: return "UNAVAILABLE"
      case .deleting: return "DELETING"
      case .deleted: return "DELETED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "AVAILABLE": self = .available
      case "UNAVAILABLE": self = .unavailable
      case "DELETING": self = .deleting
      case "DELETED": self = .deleted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .available
      case 3: self = .unavailable
      case 4: self = .deleting
      case 5: self = .deleted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .available: return try container.encode("AVAILABLE")
      case .unavailable: return try container.encode("UNAVAILABLE")
      case .deleting: return try container.encode("DELETING")
      case .deleted: return try container.encode("DELETED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.DbServerProperties"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
