// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Details of the Database System Shapes resource.
/// https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/DbSystemShapeSummary/
public struct DbSystemShape: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the Database System Shape resource with the format:
  /// projects/{project}/locations/{region}/dbSystemShapes/{db_system_shape}
  public var name: Swift.String = Swift.String()

  /// Optional. shape
  public var shape: Swift.String = Swift.String()

  /// Optional. Minimum number of database servers.
  public var minNodeCount: Swift.Int32 = Swift.Int32()

  /// Optional. Maximum number of database servers.
  public var maxNodeCount: Swift.Int32 = Swift.Int32()

  /// Optional. Minimum number of storage servers.
  public var minStorageCount: Swift.Int32 = Swift.Int32()

  /// Optional. Maximum number of storage servers.
  public var maxStorageCount: Swift.Int32 = Swift.Int32()

  /// Optional. Number of cores per node.
  public var availableCoreCountPerNode: Swift.Int32 = Swift.Int32()

  /// Optional. Memory per database server node in gigabytes.
  public var availableMemoryPerNodeGb: Swift.Int32 = Swift.Int32()

  /// Optional. Storage per storage server in terabytes.
  public var availableDataStorageTb: Swift.Int32 = Swift.Int32()

  /// Optional. Minimum core count per node.
  public var minCoreCountPerNode: Swift.Int32 = Swift.Int32()

  /// Optional. Minimum memory per node in gigabytes.
  public var minMemoryPerNodeGb: Swift.Int32 = Swift.Int32()

  /// Optional. Minimum node storage per database server in gigabytes.
  public var minDbNodeStoragePerNodeGb: Swift.Int32 = Swift.Int32()

  /// Optional. Minimum core count per node.
  public var minimumCoreCount: Swift.Int32 = Swift.Int32()

  /// Optional. Available core count.
  public var availableCoreCount: Swift.Int32 = Swift.Int32()

  /// Optional. Core count increment.
  public var coreCountIncrement: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `DbSystemShape`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DbSystemShape().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let shape = CodingKeys(stringValue: "shape")
    static let minNodeCount = CodingKeys(stringValue: "minNodeCount")
    static let maxNodeCount = CodingKeys(stringValue: "maxNodeCount")
    static let minStorageCount = CodingKeys(stringValue: "minStorageCount")
    static let maxStorageCount = CodingKeys(stringValue: "maxStorageCount")
    static let availableCoreCountPerNode = CodingKeys(stringValue: "availableCoreCountPerNode")
    static let availableMemoryPerNodeGb = CodingKeys(stringValue: "availableMemoryPerNodeGb")
    static let availableDataStorageTb = CodingKeys(stringValue: "availableDataStorageTb")
    static let minCoreCountPerNode = CodingKeys(stringValue: "minCoreCountPerNode")
    static let minMemoryPerNodeGb = CodingKeys(stringValue: "minMemoryPerNodeGb")
    static let minDbNodeStoragePerNodeGb = CodingKeys(stringValue: "minDbNodeStoragePerNodeGb")
    static let minimumCoreCount = CodingKeys(stringValue: "minimumCoreCount")
    static let availableCoreCount = CodingKeys(stringValue: "availableCoreCount")
    static let coreCountIncrement = CodingKeys(stringValue: "coreCountIncrement")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "shape",
      "minNodeCount",
      "maxNodeCount",
      "minStorageCount",
      "maxStorageCount",
      "availableCoreCountPerNode",
      "availableMemoryPerNodeGb",
      "availableDataStorageTb",
      "minCoreCountPerNode",
      "minMemoryPerNodeGb",
      "minDbNodeStoragePerNodeGb",
      "minimumCoreCount",
      "availableCoreCount",
      "coreCountIncrement",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .shape) {
      self.shape = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minNodeCount) {
      self.minNodeCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxNodeCount) {
      self.maxNodeCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minStorageCount) {
      self.minStorageCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxStorageCount) {
      self.maxStorageCount = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .availableCoreCountPerNode)
    {
      self.availableCoreCountPerNode = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .availableMemoryPerNodeGb)
    {
      self.availableMemoryPerNodeGb = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .availableDataStorageTb)
    {
      self.availableDataStorageTb = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minCoreCountPerNode) {
      self.minCoreCountPerNode = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minMemoryPerNodeGb) {
      self.minMemoryPerNodeGb = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .minDbNodeStoragePerNodeGb)
    {
      self.minDbNodeStoragePerNodeGb = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minimumCoreCount) {
      self.minimumCoreCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .availableCoreCount) {
      self.availableCoreCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .coreCountIncrement) {
      self.coreCountIncrement = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.shape, forKey: .shape)
    try container.encode(self.minNodeCount, forKey: .minNodeCount)
    try container.encode(self.maxNodeCount, forKey: .maxNodeCount)
    try container.encode(self.minStorageCount, forKey: .minStorageCount)
    try container.encode(self.maxStorageCount, forKey: .maxStorageCount)
    try container.encode(self.availableCoreCountPerNode, forKey: .availableCoreCountPerNode)
    try container.encode(self.availableMemoryPerNodeGb, forKey: .availableMemoryPerNodeGb)
    try container.encode(self.availableDataStorageTb, forKey: .availableDataStorageTb)
    try container.encode(self.minCoreCountPerNode, forKey: .minCoreCountPerNode)
    try container.encode(self.minMemoryPerNodeGb, forKey: .minMemoryPerNodeGb)
    try container.encode(self.minDbNodeStoragePerNodeGb, forKey: .minDbNodeStoragePerNodeGb)
    try container.encode(self.minimumCoreCount, forKey: .minimumCoreCount)
    try container.encode(self.availableCoreCount, forKey: .availableCoreCount)
    try container.encode(self.coreCountIncrement, forKey: .coreCountIncrement)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.DbSystemShape"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
