// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The deployment diagnostic data.
public struct DeploymentDiagnosticData: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The namespace name.
  public var namespace: Swift.String = Swift.String()

  /// Output only. The bucket name.
  public var bucket: Swift.String = Swift.String()

  /// Output only. The object name.
  public var object: Swift.String = Swift.String()

  /// Output only. The diagnostic state.
  public var diagnosticState: DeploymentDiagnosticData.DiagnosticState =
    DeploymentDiagnosticData.DiagnosticState()

  /// Output only. The time diagnostic start.
  public var diagnosticStartTime: GoogleWKT.Timestamp? = nil

  /// Output only. The time diagnostic end.
  public var diagnosticEndTime: GoogleWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DeploymentDiagnosticData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeploymentDiagnosticData().with { $0.namespace = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let namespace = CodingKeys(stringValue: "namespace")
    static let bucket = CodingKeys(stringValue: "bucket")
    static let object = CodingKeys(stringValue: "object")
    static let diagnosticState = CodingKeys(stringValue: "diagnosticState")
    static let diagnosticStartTime = CodingKeys(stringValue: "diagnosticStartTime")
    static let diagnosticEndTime = CodingKeys(stringValue: "diagnosticEndTime")

    static let _knownKeys: Set<Swift.String> = [
      "namespace",
      "bucket",
      "object",
      "diagnosticState",
      "diagnosticStartTime",
      "diagnosticEndTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .namespace) {
      self.namespace = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .bucket) {
      self.bucket = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .object) {
      self.object = value
    }
    if let value = try container.decodeIfPresent(
      DeploymentDiagnosticData.DiagnosticState.self, forKey: .diagnosticState)
    {
      self.diagnosticState = value
    }
    self.diagnosticStartTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .diagnosticStartTime)
    self.diagnosticEndTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .diagnosticEndTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.namespace, forKey: .namespace)
    try container.encode(self.bucket, forKey: .bucket)
    try container.encode(self.object, forKey: .object)
    try container.encode(self.diagnosticState, forKey: .diagnosticState)
    try container.encodeIfPresent(self.diagnosticStartTime, forKey: .diagnosticStartTime)
    try container.encodeIfPresent(self.diagnosticEndTime, forKey: .diagnosticEndTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The possible states of the diagnostic data.
  public enum DiagnosticState: Codable, Equatable, Sendable {
    /// The diagnostic state is unspecified.
    case unspecified
    /// The diagnostic is in progress.
    case inProgress
    /// The diagnostic completed successfully.
    case succeeded
    /// The diagnostic failed.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .inProgress: return 1
      case .succeeded: return 2
      case .failed: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DIAGNOSTIC_STATE_UNSPECIFIED"
      case .inProgress: return "IN_PROGRESS"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DiagnosticState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DIAGNOSTIC_STATE_UNSPECIFIED": self = .unspecified
      case "IN_PROGRESS": self = .inProgress
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DiagnosticState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .inProgress
      case 2: self = .succeeded
      case 3: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DIAGNOSTIC_STATE_UNSPECIFIED")
      case .inProgress: return try container.encode("IN_PROGRESS")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .failed: return try container.encode("FAILED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.DeploymentDiagnosticData"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
