// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The properties of an ExadbVmCluster.
public struct ExadbVmClusterProperties: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Immutable. The cluster name for Exascale vm cluster. The cluster
  /// name must begin with an alphabetic character and may contain hyphens(-) but
  /// can not contain underscores(_). It should be not more than 11 characters
  /// and is not case sensitive. OCI Cluster name.
  public var clusterName: Swift.String = Swift.String()

  /// Required. Immutable. Grid Infrastructure Version.
  public var gridImageId: Swift.String = Swift.String()

  /// Required. The number of nodes/VMs in the ExadbVmCluster.
  public var nodeCount: Swift.Int32 = Swift.Int32()

  /// Required. Immutable. The number of ECPUs enabled per node for an exadata vm
  /// cluster on exascale infrastructure.
  public var enabledEcpuCountPerNode: Swift.Int32 = Swift.Int32()

  /// Optional. Immutable. The number of additional ECPUs per node for an Exadata
  /// VM cluster on exascale infrastructure.
  public var additionalEcpuCountPerNode: Swift.Int32 = Swift.Int32()

  /// Required. Immutable. Total storage details for the ExadbVmCluster.
  public var vmFileSystemStorage: ExadbVmClusterStorageDetails? = nil

  /// Optional. Immutable. The license type of the ExadbVmCluster.
  public var licenseModel: ExadbVmClusterProperties.LicenseModel =
    ExadbVmClusterProperties.LicenseModel()

  /// Required. Immutable. The name of ExascaleDbStorageVault associated with the
  /// ExadbVmCluster. It can refer to an existing ExascaleDbStorageVault. Or a
  /// new one can be created during the ExadbVmCluster creation (requires
  /// storage_vault_properties to be set).
  /// Format:
  /// projects/{project}/locations/{location}/exascaleDbStorageVaults/{exascale_db_storage_vault}
  public var exascaleDbStorageVault: Swift.String = Swift.String()

  /// Required. Immutable. Prefix for VM cluster host names.
  public var hostnamePrefix: Swift.String = Swift.String()

  /// Output only. The hostname of the ExadbVmCluster.
  public var hostname: Swift.String = Swift.String()

  /// Required. Immutable. The SSH public keys for the ExadbVmCluster.
  public var sshPublicKeys: [Swift.String] = []

  /// Optional. Immutable. Indicates user preference for data collection options.
  public var dataCollectionOptions: DataCollectionOptionsCommon? = nil

  /// Optional. Immutable. The time zone of the ExadbVmCluster.
  public var timeZone: GoogleType.TimeZone? = nil

  /// Output only. State of the cluster.
  public var lifecycleState: ExadbVmClusterProperties.ExadbVmClusterLifecycleState =
    ExadbVmClusterProperties.ExadbVmClusterLifecycleState()

  /// Required. Immutable. The shape attribute of the VM cluster. The type of
  /// Exascale storage used for Exadata VM cluster. The default is SMART_STORAGE
  /// which supports Oracle Database 23ai and later
  public var shapeAttribute: ExadbVmClusterProperties.ShapeAttribute =
    ExadbVmClusterProperties.ShapeAttribute()

  /// Output only. Memory per VM (GB) (Read-only): Shows the amount of memory
  /// allocated to each VM. Memory is calculated based on 2.75 GB per Total
  /// ECPUs.
  public var memorySizeGb: Swift.Int32 = Swift.Int32()

  /// Optional. Immutable. SCAN listener port - TCP
  public var scanListenerPortTcp: Swift.Int32 = Swift.Int32()

  /// Output only. Deep link to the OCI console to view this resource.
  public var ociUri: Swift.String = Swift.String()

  /// Output only. The Oracle Grid Infrastructure (GI) software version.
  public var giVersion: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExadbVmClusterProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExadbVmClusterProperties().with { $0.clusterName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let clusterName = CodingKeys(stringValue: "clusterName")
    static let gridImageId = CodingKeys(stringValue: "gridImageId")
    static let nodeCount = CodingKeys(stringValue: "nodeCount")
    static let enabledEcpuCountPerNode = CodingKeys(stringValue: "enabledEcpuCountPerNode")
    static let additionalEcpuCountPerNode = CodingKeys(stringValue: "additionalEcpuCountPerNode")
    static let vmFileSystemStorage = CodingKeys(stringValue: "vmFileSystemStorage")
    static let licenseModel = CodingKeys(stringValue: "licenseModel")
    static let exascaleDbStorageVault = CodingKeys(stringValue: "exascaleDbStorageVault")
    static let hostnamePrefix = CodingKeys(stringValue: "hostnamePrefix")
    static let hostname = CodingKeys(stringValue: "hostname")
    static let sshPublicKeys = CodingKeys(stringValue: "sshPublicKeys")
    static let dataCollectionOptions = CodingKeys(stringValue: "dataCollectionOptions")
    static let timeZone = CodingKeys(stringValue: "timeZone")
    static let lifecycleState = CodingKeys(stringValue: "lifecycleState")
    static let shapeAttribute = CodingKeys(stringValue: "shapeAttribute")
    static let memorySizeGb = CodingKeys(stringValue: "memorySizeGb")
    static let scanListenerPortTcp = CodingKeys(stringValue: "scanListenerPortTcp")
    static let ociUri = CodingKeys(stringValue: "ociUri")
    static let giVersion = CodingKeys(stringValue: "giVersion")

    static let _knownKeys: Set<Swift.String> = [
      "clusterName",
      "gridImageId",
      "nodeCount",
      "enabledEcpuCountPerNode",
      "additionalEcpuCountPerNode",
      "vmFileSystemStorage",
      "licenseModel",
      "exascaleDbStorageVault",
      "hostnamePrefix",
      "hostname",
      "sshPublicKeys",
      "dataCollectionOptions",
      "timeZone",
      "lifecycleState",
      "shapeAttribute",
      "memorySizeGb",
      "scanListenerPortTcp",
      "ociUri",
      "giVersion",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clusterName) {
      self.clusterName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gridImageId) {
      self.gridImageId = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .nodeCount) {
      self.nodeCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .enabledEcpuCountPerNode)
    {
      self.enabledEcpuCountPerNode = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .additionalEcpuCountPerNode)
    {
      self.additionalEcpuCountPerNode = value
    }
    self.vmFileSystemStorage = try container.decodeIfPresent(
      ExadbVmClusterStorageDetails.self, forKey: .vmFileSystemStorage)
    if let value = try container.decodeIfPresent(
      ExadbVmClusterProperties.LicenseModel.self, forKey: .licenseModel)
    {
      self.licenseModel = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .exascaleDbStorageVault)
    {
      self.exascaleDbStorageVault = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostnamePrefix) {
      self.hostnamePrefix = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostname) {
      self.hostname = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .sshPublicKeys) {
      self.sshPublicKeys = value
    }
    self.dataCollectionOptions = try container.decodeIfPresent(
      DataCollectionOptionsCommon.self, forKey: .dataCollectionOptions)
    self.timeZone = try container.decodeIfPresent(GoogleType.TimeZone.self, forKey: .timeZone)
    if let value = try container.decodeIfPresent(
      ExadbVmClusterProperties.ExadbVmClusterLifecycleState.self, forKey: .lifecycleState)
    {
      self.lifecycleState = value
    }
    if let value = try container.decodeIfPresent(
      ExadbVmClusterProperties.ShapeAttribute.self, forKey: .shapeAttribute)
    {
      self.shapeAttribute = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .memorySizeGb) {
      self.memorySizeGb = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .scanListenerPortTcp) {
      self.scanListenerPortTcp = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ociUri) {
      self.ociUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .giVersion) {
      self.giVersion = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.clusterName, forKey: .clusterName)
    try container.encode(self.gridImageId, forKey: .gridImageId)
    try container.encode(self.nodeCount, forKey: .nodeCount)
    try container.encode(self.enabledEcpuCountPerNode, forKey: .enabledEcpuCountPerNode)
    try container.encode(self.additionalEcpuCountPerNode, forKey: .additionalEcpuCountPerNode)
    try container.encodeIfPresent(self.vmFileSystemStorage, forKey: .vmFileSystemStorage)
    try container.encode(self.licenseModel, forKey: .licenseModel)
    try container.encode(self.exascaleDbStorageVault, forKey: .exascaleDbStorageVault)
    try container.encode(self.hostnamePrefix, forKey: .hostnamePrefix)
    try container.encode(self.hostname, forKey: .hostname)
    try container.encode(self.sshPublicKeys, forKey: .sshPublicKeys)
    try container.encodeIfPresent(self.dataCollectionOptions, forKey: .dataCollectionOptions)
    try container.encodeIfPresent(self.timeZone, forKey: .timeZone)
    try container.encode(self.lifecycleState, forKey: .lifecycleState)
    try container.encode(self.shapeAttribute, forKey: .shapeAttribute)
    try container.encode(self.memorySizeGb, forKey: .memorySizeGb)
    try container.encode(self.scanListenerPortTcp, forKey: .scanListenerPortTcp)
    try container.encode(self.ociUri, forKey: .ociUri)
    try container.encode(self.giVersion, forKey: .giVersion)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The Oracle license model that applies to the ExaScale VM cluster
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum LicenseModel: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Default is license included.
    case licenseIncluded
    /// Bring your own license.
    case bringYourOwnLicense
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .licenseIncluded: return 1
      case .bringYourOwnLicense: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "LICENSE_MODEL_UNSPECIFIED"
      case .licenseIncluded: return "LICENSE_INCLUDED"
      case .bringYourOwnLicense: return "BRING_YOUR_OWN_LICENSE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LicenseModel/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "LICENSE_MODEL_UNSPECIFIED": self = .unspecified
      case "LICENSE_INCLUDED": self = .licenseIncluded
      case "BRING_YOUR_OWN_LICENSE": self = .bringYourOwnLicense
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LicenseModel/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .licenseIncluded
      case 2: self = .bringYourOwnLicense
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("LICENSE_MODEL_UNSPECIFIED")
      case .licenseIncluded: return try container.encode("LICENSE_INCLUDED")
      case .bringYourOwnLicense: return try container.encode("BRING_YOUR_OWN_LICENSE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The various lifecycle states of the VM cluster.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ExadbVmClusterLifecycleState: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Indicates that the resource is in provisioning state.
    case provisioning
    /// Indicates that the resource is in available state.
    case available
    /// Indicates that the resource is in updating state.
    case updating
    /// Indicates that the resource is in terminating state.
    case terminating
    /// Indicates that the resource is in terminated state.
    case terminated
    /// Indicates that the resource is in failed state.
    case failed
    /// Indicates that the resource is in maintenance in progress state.
    case maintenanceInProgress
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .provisioning: return 1
      case .available: return 2
      case .updating: return 3
      case .terminating: return 4
      case .terminated: return 5
      case .failed: return 6
      case .maintenanceInProgress: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EXADB_VM_CLUSTER_LIFECYCLE_STATE_UNSPECIFIED"
      case .provisioning: return "PROVISIONING"
      case .available: return "AVAILABLE"
      case .updating: return "UPDATING"
      case .terminating: return "TERMINATING"
      case .terminated: return "TERMINATED"
      case .failed: return "FAILED"
      case .maintenanceInProgress: return "MAINTENANCE_IN_PROGRESS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ExadbVmClusterLifecycleState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EXADB_VM_CLUSTER_LIFECYCLE_STATE_UNSPECIFIED": self = .unspecified
      case "PROVISIONING": self = .provisioning
      case "AVAILABLE": self = .available
      case "UPDATING": self = .updating
      case "TERMINATING": self = .terminating
      case "TERMINATED": self = .terminated
      case "FAILED": self = .failed
      case "MAINTENANCE_IN_PROGRESS": self = .maintenanceInProgress
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ExadbVmClusterLifecycleState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .provisioning
      case 2: self = .available
      case 3: self = .updating
      case 4: self = .terminating
      case 5: self = .terminated
      case 6: self = .failed
      case 7: self = .maintenanceInProgress
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("EXADB_VM_CLUSTER_LIFECYCLE_STATE_UNSPECIFIED")
      case .provisioning: return try container.encode("PROVISIONING")
      case .available: return try container.encode("AVAILABLE")
      case .updating: return try container.encode("UPDATING")
      case .terminating: return try container.encode("TERMINATING")
      case .terminated: return try container.encode("TERMINATED")
      case .failed: return try container.encode("FAILED")
      case .maintenanceInProgress: return try container.encode("MAINTENANCE_IN_PROGRESS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The shape attribute of the VM cluster. The type of Exascale storage used
  /// for Exadata VM cluster. The default is SMART_STORAGE which supports Oracle
  /// Database 23ai and later
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ShapeAttribute: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Indicates that the resource is in smart storage.
    case smartStorage
    /// Indicates that the resource is in block storage.
    case blockStorage
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .smartStorage: return 1
      case .blockStorage: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SHAPE_ATTRIBUTE_UNSPECIFIED"
      case .smartStorage: return "SMART_STORAGE"
      case .blockStorage: return "BLOCK_STORAGE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ShapeAttribute/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SHAPE_ATTRIBUTE_UNSPECIFIED": self = .unspecified
      case "SMART_STORAGE": self = .smartStorage
      case "BLOCK_STORAGE": self = .blockStorage
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ShapeAttribute/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .smartStorage
      case 2: self = .blockStorage
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SHAPE_ATTRIBUTE_UNSPECIFIED")
      case .smartStorage: return try container.encode("SMART_STORAGE")
      case .blockStorage: return try container.encode("BLOCK_STORAGE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.ExadbVmClusterProperties"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
