// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The maintenance configuration of the GoldengateDeployment.
public struct GoldengateMaintenanceConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. By default auto upgrade for interim releases are not enabled. If
  /// auto-upgrade is enabled for interim release,  you have to specify
  /// interim_release_upgrade_period_days too.
  public var isInterimReleaseAutoUpgradeEnabled: Swift.Bool = Swift.Bool()

  /// Optional. Defines auto upgrade period for interim releases. This period
  /// must be shorter or equal to bundle release upgrade period.
  public var interimReleaseUpgradePeriodDays: Swift.Int32 = Swift.Int32()

  /// Optional. Defines auto upgrade period for bundle releases. Manually
  /// configured period cannot be longer than service defined period for bundle
  /// releases. This period must be shorter or equal to major release upgrade
  /// period. Not passing this field during create will equate to using the
  /// service default.
  public var bundleReleaseUpgradePeriodDays: Swift.Int32 = Swift.Int32()

  /// Optional. Defines auto upgrade period for major releases. Manually
  /// configured period cannot be longer than service defined period for major
  /// releases. Not passing this field during create will equate to using the
  /// service default.
  public var majorReleaseUpgradePeriodDays: Swift.Int32 = Swift.Int32()

  /// Optional. Defines auto upgrade period for releases with security fix.
  /// Manually configured period cannot be longer than service defined period for
  /// security releases. Not passing this field during create will equate to
  /// using the service default.
  public var securityPatchUpgradePeriodDays: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `GoldengateMaintenanceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GoldengateMaintenanceConfig().with { $0.isInterimReleaseAutoUpgradeEnabled = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.GoldengateMaintenanceConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
