// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The properties of GoldengateAmazonS3Connection.
public struct GoldengateAmazonS3ConnectionProperties: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The technology type of AmazonS3Connection.
  public var technologyType: Swift.String = Swift.String()

  /// Optional. Access key ID to access the Amazon S3 bucket.
  public var accessKeyId: Swift.String = Swift.String()

  /// Optional. Secret access key to access the Amazon S3 bucket.
  public var secretAccessKeySecret: Swift.String = Swift.String()

  /// Optional. The Amazon Endpoint for S3.
  public var endpoint: Swift.String = Swift.String()

  /// Optional. The name of the AWS region where the bucket is created.
  public var region: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GoldengateAmazonS3ConnectionProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GoldengateAmazonS3ConnectionProperties().with { $0.technologyType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let technologyType = CodingKeys(stringValue: "technologyType")
    static let accessKeyId = CodingKeys(stringValue: "accessKeyId")
    static let secretAccessKeySecret = CodingKeys(stringValue: "secretAccessKeySecret")
    static let endpoint = CodingKeys(stringValue: "endpoint")
    static let region = CodingKeys(stringValue: "region")

    static let _knownKeys: Set<Swift.String> = [
      "technologyType",
      "accessKeyId",
      "secretAccessKeySecret",
      "endpoint",
      "region",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .technologyType) {
      self.technologyType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .accessKeyId) {
      self.accessKeyId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .secretAccessKeySecret)
    {
      self.secretAccessKeySecret = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .endpoint) {
      self.endpoint = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .region) {
      self.region = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.technologyType, forKey: .technologyType)
    try container.encode(self.accessKeyId, forKey: .accessKeyId)
    try container.encode(self.secretAccessKeySecret, forKey: .secretAccessKeySecret)
    try container.encode(self.endpoint, forKey: .endpoint)
    try container.encode(self.region, forKey: .region)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.oracledatabase.v1.GoldengateAmazonS3ConnectionProperties"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
