// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The properties of GoldengateAmazonKinesisConnection.
public struct GoldengateAmazonKinesisConnectionProperties: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// Optional. The technology type of AmazonKinesisConnection.
  public var technologyType: Swift.String = Swift.String()

  /// Optional. Access key ID to access the Amazon Kinesis.
  public var accessKeyId: Swift.String = Swift.String()

  /// Optional. Secret access key to access the Amazon Kinesis.
  public var secretAccessKeySecret: Swift.String = Swift.String()

  /// Optional. The endpoint URL of the Amazon Kinesis service.
  /// e.g.: 'https://kinesis.us-east-1.amazonaws.com'
  /// If not provided, Goldengate will default to
  /// 'https://kinesis.<region>.amazonaws.com'.
  public var endpoint: Swift.String = Swift.String()

  /// Optional. The name of the AWS region.
  /// If not provided, Goldengate will default to 'us-west-1'.
  public var awsRegion: Swift.String = Swift.String()

  /// Initialize a new instance of `GoldengateAmazonKinesisConnectionProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GoldengateAmazonKinesisConnectionProperties().with { $0.technologyType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.oracledatabase.v1.GoldengateAmazonKinesisConnectionProperties"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
