// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Properties of GoldengateDeployment.
public struct GoldengateDeploymentProperties: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. OCID of the GoldengateDeployment.
  public var ocid: Swift.String = Swift.String()

  /// Output only. State of the GoldengateDeployment.
  public var lifecycleState: GoldengateDeploymentProperties.GoldengateDeploymentLifecycleState =
    GoldengateDeploymentProperties.GoldengateDeploymentLifecycleState()

  /// Optional. The Oracle license model that applies to a Deployment.
  public var licenseModel: GoldengateDeploymentProperties.LicenseModel =
    GoldengateDeploymentProperties.LicenseModel()

  /// Optional. The environment type of the GoldengateDeployment.
  public var environmentType: Swift.String = Swift.String()

  /// Optional. The Minimum number of OCPUs to be made available for this
  /// Deployment.
  public var cpuCoreCount: Swift.Int32 = Swift.Int32()

  /// Optional. Indicates if auto scaling is enabled for the Deployment's CPU
  /// core count.
  public var isAutoScalingEnabled: Swift.Bool = Swift.Bool()

  /// Optional. The description of the GoldengateDeployment.
  public var description: Swift.String = Swift.String()

  /// Required. A valid Goldengate Deployment type. For a list of supported
  /// types, use the `ListGoldengateDeploymentTypes` operation.
  public var deploymentType: Swift.String = Swift.String()

  /// Required. The ogg data of the GoldengateDeployment.
  public var oggData: GoldengateOggDeployment? = nil

  /// Optional. The maintenance window of the GoldengateDeployment.
  public var maintenanceWindow: GoldengateMaintenanceWindow? = nil

  /// Optional. The maintenance configuration of the GoldengateDeployment.
  public var maintenanceConfig: GoldengateMaintenanceConfig? = nil

  /// Output only. The Fully Qualified Domain Name of the GoldengateDeployment.
  public var fqdn: Swift.String = Swift.String()

  /// Output only. The lifecycle sub-state of the GoldengateDeployment.
  public var lifecycleSubState:
    GoldengateDeploymentProperties.GoldengateDeploymentLifecycleSubState =
      GoldengateDeploymentProperties.GoldengateDeploymentLifecycleSubState()

  /// Output only. The category of the GoldengateDeployment.
  public var category: GoldengateDeploymentProperties.GoldengateDeploymentCategory =
    GoldengateDeploymentProperties.GoldengateDeploymentCategory()

  /// Output only. The deployment backup id of the GoldengateDeployment.
  public var deploymentBackupId: Swift.String = Swift.String()

  /// Output only. The time the GoldengateDeployment was updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The lifecycle details of the GoldengateDeployment.
  public var lifecycleDetails: Swift.String = Swift.String()

  /// Output only. Whether the GoldengateDeployment is healthy.
  public var healthy: Swift.Bool = Swift.Bool()

  /// Output only. The load balancer subnet id of the GoldengateDeployment.
  public var loadBalancerSubnetId: Swift.String = Swift.String()

  /// Output only. The load balancer id of the GoldengateDeployment.
  public var loadBalancerId: Swift.String = Swift.String()

  /// Output only. The nsg ids of the GoldengateDeployment.
  public var nsgIds: [Swift.String] = []

  /// Output only. Whether the GoldengateDeployment is public.
  public var isPublic: Swift.Bool = Swift.Bool()

  /// Output only. The public ip address of the GoldengateDeployment.
  public var publicIpAddress: Swift.String = Swift.String()

  /// Output only. The private ip address of the GoldengateDeployment.
  public var privateIpAddress: Swift.String = Swift.String()

  /// Output only. The deployment url of the GoldengateDeployment.
  public var deploymentUrl: Swift.String = Swift.String()

  /// Output only. Whether the GoldengateDeployment is of the latest version.
  public var isLatestVersion: Swift.Bool = Swift.Bool()

  /// Output only. The time upgrade required of the GoldengateDeployment.
  public var upgradeRequiredTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The storage utilization in bytes of the GoldengateDeployment.
  public var storageUtilizationBytes: Swift.Int64 = Swift.Int64()

  /// Output only. Whether storage utilization limit is exceeded of the
  /// GoldengateDeployment.
  public var isStorageUtilizationLimitExceeded: Swift.Bool = Swift.Bool()

  /// Output only. The deployment diagnostic data of the GoldengateDeployment.
  public var deploymentDiagnosticData: DeploymentDiagnosticData? = nil

  /// Output only. The backup schedule of the GoldengateDeployment.
  public var backupSchedule: GoldengateBackupSchedule? = nil

  /// Output only. The time of next maintenance of the GoldengateDeployment.
  public var nextMaintenanceTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The next maintenance action type of the GoldengateDeployment.
  public var nextMaintenanceActionType: GoldengateDeploymentProperties.NextMaintenanceActionType =
    GoldengateDeploymentProperties.NextMaintenanceActionType()

  /// Output only. The next maintenance description of the GoldengateDeployment.
  public var nextMaintenanceDescription: Swift.String = Swift.String()

  /// Output only. The time ogg version supported until of the
  /// GoldengateDeployment.
  public var oggVersionSupportEndTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The ingress ips of the GoldengateDeployment.
  public var ingressIps: [IngressIp] = []

  /// Output only. The deployment role of the GoldengateDeployment.
  public var deploymentRole: GoldengateDeploymentProperties.GoldengateDeploymentRoleType =
    GoldengateDeploymentProperties.GoldengateDeploymentRoleType()

  /// Output only. The time last backup scheduled of the GoldengateDeployment.
  public var lastBackupScheduleTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time next backup scheduled of the GoldengateDeployment.
  public var nextBackupScheduleTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time when the role of the GoldengateDeployment was
  /// changed.
  public var roleChangeTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The locks of the GoldengateDeployment.
  public var locks: [GoldengateDeploymentLock] = []

  /// Output only. The placements of the GoldengateDeployment.
  public var placements: [GoldengatePlacement] = []

  /// Initialize a new instance of `GoldengateDeploymentProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GoldengateDeploymentProperties().with { $0.ocid = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The various lifecycle states of the GoldengateDeployment.
  public enum GoldengateDeploymentLifecycleState: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// The deployment is being created.
    case creating
    /// The deployment is being updated.
    case updating
    /// The deployment is active.
    case active
    /// The deployment is inactive.
    case inactive
    /// The deployment is being deleted.
    case deleting
    /// The deployment is deleted.
    case deleted
    /// The deployment failed.
    case failed
    /// The deployment needs attention.
    case needsAttention
    /// The deployment is in progress.
    case inProgress
    /// The deployment is canceling.
    case cancelling
    /// The deployment is canceled.
    case cancelled
    /// The deployment succeeded.
    case succeeded
    /// The deployment is waiting.
    case waiting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .updating: return 2
      case .active: return 3
      case .inactive: return 4
      case .deleting: return 5
      case .deleted: return 6
      case .failed: return 7
      case .needsAttention: return 8
      case .inProgress: return 9
      case .cancelling: return 10
      case .cancelled: return 11
      case .succeeded: return 12
      case .waiting: return 13
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "GOLDENGATE_DEPLOYMENT_LIFECYCLE_STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .updating: return "UPDATING"
      case .active: return "ACTIVE"
      case .inactive: return "INACTIVE"
      case .deleting: return "DELETING"
      case .deleted: return "DELETED"
      case .failed: return "FAILED"
      case .needsAttention: return "NEEDS_ATTENTION"
      case .inProgress: return "IN_PROGRESS"
      case .cancelling: return "CANCELLING"
      case .cancelled: return "CANCELLED"
      case .succeeded: return "SUCCEEDED"
      case .waiting: return "WAITING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:GoldengateDeploymentLifecycleState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "GOLDENGATE_DEPLOYMENT_LIFECYCLE_STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "UPDATING": self = .updating
      case "ACTIVE": self = .active
      case "INACTIVE": self = .inactive
      case "DELETING": self = .deleting
      case "DELETED": self = .deleted
      case "FAILED": self = .failed
      case "NEEDS_ATTENTION": self = .needsAttention
      case "IN_PROGRESS": self = .inProgress
      case "CANCELLING": self = .cancelling
      case "CANCELLED": self = .cancelled
      case "SUCCEEDED": self = .succeeded
      case "WAITING": self = .waiting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:GoldengateDeploymentLifecycleState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .updating
      case 3: self = .active
      case 4: self = .inactive
      case 5: self = .deleting
      case 6: self = .deleted
      case 7: self = .failed
      case 8: self = .needsAttention
      case 9: self = .inProgress
      case 10: self = .cancelling
      case 11: self = .cancelled
      case 12: self = .succeeded
      case 13: self = .waiting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .updating: return try container.encode(2)
      case .active: return try container.encode(3)
      case .inactive: return try container.encode(4)
      case .deleting: return try container.encode(5)
      case .deleted: return try container.encode(6)
      case .failed: return try container.encode(7)
      case .needsAttention: return try container.encode(8)
      case .inProgress: return try container.encode(9)
      case .cancelling: return try container.encode(10)
      case .cancelled: return try container.encode(11)
      case .succeeded: return try container.encode(12)
      case .waiting: return try container.encode(13)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The license model of the GoldengateDeployment.
  public enum LicenseModel: Codable, Equatable, Sendable {
    /// The license model is unspecified.
    case unspecified
    /// The license model is included.
    case licenseIncluded
    /// The license model is bring your own license.
    case bringYourOwnLicense
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .licenseIncluded: return 1
      case .bringYourOwnLicense: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "LICENSE_MODEL_UNSPECIFIED"
      case .licenseIncluded: return "LICENSE_INCLUDED"
      case .bringYourOwnLicense: return "BRING_YOUR_OWN_LICENSE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LicenseModel/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "LICENSE_MODEL_UNSPECIFIED": self = .unspecified
      case "LICENSE_INCLUDED": self = .licenseIncluded
      case "BRING_YOUR_OWN_LICENSE": self = .bringYourOwnLicense
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LicenseModel/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .licenseIncluded
      case 2: self = .bringYourOwnLicense
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .licenseIncluded: return try container.encode(1)
      case .bringYourOwnLicense: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The various lifecycle sub-states of the GoldengateDeployment.
  public enum GoldengateDeploymentLifecycleSubState: Codable, Equatable, Sendable {
    /// The lifecycle sub-state is unspecified.
    case unspecified
    /// The deployment is recovering.
    case recovering
    /// The deployment is starting.
    case starting
    /// The deployment is stopping.
    case stopping
    /// The deployment is moving.
    case moving
    /// The deployment is upgrading.
    case upgrading
    /// The deployment is restoring.
    case restoring
    /// The deployment is backing up.
    case backingUp
    /// The deployment is rolling back.
    case rollingBack
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .recovering: return 1
      case .starting: return 2
      case .stopping: return 3
      case .moving: return 4
      case .upgrading: return 5
      case .restoring: return 6
      case .backingUp: return 7
      case .rollingBack: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "GOLDENGATE_DEPLOYMENT_LIFECYCLE_SUB_STATE_UNSPECIFIED"
      case .recovering: return "RECOVERING"
      case .starting: return "STARTING"
      case .stopping: return "STOPPING"
      case .moving: return "MOVING"
      case .upgrading: return "UPGRADING"
      case .restoring: return "RESTORING"
      case .backingUp: return "BACKING_UP"
      case .rollingBack: return "ROLLING_BACK"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:GoldengateDeploymentLifecycleSubState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "GOLDENGATE_DEPLOYMENT_LIFECYCLE_SUB_STATE_UNSPECIFIED": self = .unspecified
      case "RECOVERING": self = .recovering
      case "STARTING": self = .starting
      case "STOPPING": self = .stopping
      case "MOVING": self = .moving
      case "UPGRADING": self = .upgrading
      case "RESTORING": self = .restoring
      case "BACKING_UP": self = .backingUp
      case "ROLLING_BACK": self = .rollingBack
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:GoldengateDeploymentLifecycleSubState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .recovering
      case 2: self = .starting
      case 3: self = .stopping
      case 4: self = .moving
      case 5: self = .upgrading
      case 6: self = .restoring
      case 7: self = .backingUp
      case 8: self = .rollingBack
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .recovering: return try container.encode(1)
      case .starting: return try container.encode(2)
      case .stopping: return try container.encode(3)
      case .moving: return try container.encode(4)
      case .upgrading: return try container.encode(5)
      case .restoring: return try container.encode(6)
      case .backingUp: return try container.encode(7)
      case .rollingBack: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The category of the GoldengateDeployment.
  public enum GoldengateDeploymentCategory: Codable, Equatable, Sendable {
    /// The category is unspecified.
    case unspecified
    /// The deployment is data replication.
    case dataReplication
    /// The deployment is data transforms.
    case dataTransforms
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .dataReplication: return 1
      case .dataTransforms: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "GOLDENGATE_DEPLOYMENT_CATEGORY_UNSPECIFIED"
      case .dataReplication: return "DATA_REPLICATION"
      case .dataTransforms: return "DATA_TRANSFORMS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:GoldengateDeploymentCategory/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "GOLDENGATE_DEPLOYMENT_CATEGORY_UNSPECIFIED": self = .unspecified
      case "DATA_REPLICATION": self = .dataReplication
      case "DATA_TRANSFORMS": self = .dataTransforms
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:GoldengateDeploymentCategory/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .dataReplication
      case 2: self = .dataTransforms
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .dataReplication: return try container.encode(1)
      case .dataTransforms: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The various next maintenance action types of the GoldengateDeployment.
  public enum NextMaintenanceActionType: Codable, Equatable, Sendable {
    /// The next maintenance action type is unspecified.
    case unspecified
    /// The next maintenance action type is upgrade.
    case upgrade
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .upgrade: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "NEXT_MAINTENANCE_ACTION_TYPE_UNSPECIFIED"
      case .upgrade: return "UPGRADE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:NextMaintenanceActionType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "NEXT_MAINTENANCE_ACTION_TYPE_UNSPECIFIED": self = .unspecified
      case "UPGRADE": self = .upgrade
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:NextMaintenanceActionType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .upgrade
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .upgrade: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The deployment role type of the GoldengateDeployment.
  public enum GoldengateDeploymentRoleType: Codable, Equatable, Sendable {
    /// The deployment role type is unspecified.
    case unspecified
    /// The deployment role type is primary.
    case primary
    /// The deployment role type is standby.
    case standby
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .primary: return 1
      case .standby: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "GOLDENGATE_DEPLOYMENT_ROLE_TYPE_UNSPECIFIED"
      case .primary: return "PRIMARY"
      case .standby: return "STANDBY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:GoldengateDeploymentRoleType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "GOLDENGATE_DEPLOYMENT_ROLE_TYPE_UNSPECIFIED": self = .unspecified
      case "PRIMARY": self = .primary
      case "STANDBY": self = .standby
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:GoldengateDeploymentRoleType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .primary
      case 2: self = .standby
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .primary: return try container.encode(1)
      case .standby: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.GoldengateDeploymentProperties"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
