// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Details of the Goldengate Connection Type resource.
public struct GoldengateConnectionType: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The name of the Goldengate Connection Type resource with the
  /// format:
  /// projects/{project}/locations/{region}/goldengateConnectionTypes/{goldengate_connection_type}
  public var name: Swift.String = Swift.String()

  /// Output only. The connection type of the Goldengate Connection Type
  /// resource.
  public var connectionType: GoldengateConnectionType.ConnectionType =
    GoldengateConnectionType.ConnectionType()

  /// Output only. The technology type of the Goldengate Connection Type
  /// resource.
  public var technologyTypes: [Swift.String] = []

  /// Initialize a new instance of `GoldengateConnectionType`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GoldengateConnectionType().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The connection type of the Goldengate Connection Type resource.
  public enum ConnectionType: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Goldengate Connection Type category is GOLDENGATE.
    case goldengate
    /// Goldengate Connection Type category is KAFKA.
    case kafka
    /// Goldengate Connection Type category is KAFKA_SCHEMA_REGISTRY.
    case kafkaSchemaRegistry
    /// Goldengate Connection Type category is MYSQL.
    case mysql
    /// Goldengate Connection Type category is JAVA_MESSAGE_SERVICE.
    case javaMessageService
    /// Goldengate Connection Type category is MICROSOFT_SQLSERVER.
    case microsoftSqlserver
    /// Goldengate Connection Type category is OCI_OBJECT_STORAGE.
    case ociObjectStorage
    /// Goldengate Connection Type category is ORACLE.
    case oracle
    /// Goldengate Connection Type category is AZURE_DATA_LAKE_STORAGE.
    case azureDataLakeStorage
    /// Goldengate Connection Type category is POSTGRESQL.
    case postgresql
    /// Goldengate Connection Type category is AZURE_SYNAPSE_ANALYTICS.
    case azureSynapseAnalytics
    /// Goldengate Connection Type category is SNOWFLAKE.
    case snowflake
    /// Goldengate Connection Type category is AMAZON_S3.
    case amazonS3
    /// Goldengate Connection Type category is HDFS.
    case hdfs
    /// Goldengate Connection Type category is ORACLE_AI_DATA_PLATFORM.
    case oracleAiDataPlatform
    /// Goldengate Connection Type category is ORACLE_NOSQL.
    case oracleNosql
    /// Goldengate Connection Type category is MONGODB.
    case mongodb
    /// Goldengate Connection Type category is AMAZON_KINESIS.
    case amazonKinesis
    /// Goldengate Connection Type category is AMAZON_REDSHIFT.
    case amazonRedshift
    /// Goldengate Connection Type category is DB2.
    case db2
    /// Goldengate Connection Type category is REDIS.
    case redis
    /// Goldengate Connection Type category is ELASTICSEARCH.
    case elasticsearch
    /// Goldengate Connection Type category is GENERIC.
    case generic
    /// Goldengate Connection Type category is GOOGLE_CLOUD_STORAGE.
    case googleCloudStorage
    /// Goldengate Connection Type category is GOOGLE_BIGQUERY.
    case googleBigquery
    /// Goldengate Connection Type category is DATABRICKS.
    case databricks
    /// Goldengate Connection Type category is GOOGLE_PUBSUB.
    case googlePubsub
    /// Goldengate Connection Type category is MICROSOFT_FABRIC.
    case microsoftFabric
    /// Goldengate Connection Type category is ICEBERG.
    case iceberg
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .goldengate: return 1
      case .kafka: return 2
      case .kafkaSchemaRegistry: return 3
      case .mysql: return 4
      case .javaMessageService: return 5
      case .microsoftSqlserver: return 6
      case .ociObjectStorage: return 7
      case .oracle: return 8
      case .azureDataLakeStorage: return 9
      case .postgresql: return 10
      case .azureSynapseAnalytics: return 11
      case .snowflake: return 12
      case .amazonS3: return 13
      case .hdfs: return 14
      case .oracleAiDataPlatform: return 15
      case .oracleNosql: return 16
      case .mongodb: return 17
      case .amazonKinesis: return 18
      case .amazonRedshift: return 19
      case .db2: return 20
      case .redis: return 21
      case .elasticsearch: return 22
      case .generic: return 23
      case .googleCloudStorage: return 24
      case .googleBigquery: return 25
      case .databricks: return 26
      case .googlePubsub: return 27
      case .microsoftFabric: return 28
      case .iceberg: return 29
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CONNECTION_TYPE_UNSPECIFIED"
      case .goldengate: return "GOLDENGATE"
      case .kafka: return "KAFKA"
      case .kafkaSchemaRegistry: return "KAFKA_SCHEMA_REGISTRY"
      case .mysql: return "MYSQL"
      case .javaMessageService: return "JAVA_MESSAGE_SERVICE"
      case .microsoftSqlserver: return "MICROSOFT_SQLSERVER"
      case .ociObjectStorage: return "OCI_OBJECT_STORAGE"
      case .oracle: return "ORACLE"
      case .azureDataLakeStorage: return "AZURE_DATA_LAKE_STORAGE"
      case .postgresql: return "POSTGRESQL"
      case .azureSynapseAnalytics: return "AZURE_SYNAPSE_ANALYTICS"
      case .snowflake: return "SNOWFLAKE"
      case .amazonS3: return "AMAZON_S3"
      case .hdfs: return "HDFS"
      case .oracleAiDataPlatform: return "ORACLE_AI_DATA_PLATFORM"
      case .oracleNosql: return "ORACLE_NOSQL"
      case .mongodb: return "MONGODB"
      case .amazonKinesis: return "AMAZON_KINESIS"
      case .amazonRedshift: return "AMAZON_REDSHIFT"
      case .db2: return "DB2"
      case .redis: return "REDIS"
      case .elasticsearch: return "ELASTICSEARCH"
      case .generic: return "GENERIC"
      case .googleCloudStorage: return "GOOGLE_CLOUD_STORAGE"
      case .googleBigquery: return "GOOGLE_BIGQUERY"
      case .databricks: return "DATABRICKS"
      case .googlePubsub: return "GOOGLE_PUBSUB"
      case .microsoftFabric: return "MICROSOFT_FABRIC"
      case .iceberg: return "ICEBERG"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConnectionType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CONNECTION_TYPE_UNSPECIFIED": self = .unspecified
      case "GOLDENGATE": self = .goldengate
      case "KAFKA": self = .kafka
      case "KAFKA_SCHEMA_REGISTRY": self = .kafkaSchemaRegistry
      case "MYSQL": self = .mysql
      case "JAVA_MESSAGE_SERVICE": self = .javaMessageService
      case "MICROSOFT_SQLSERVER": self = .microsoftSqlserver
      case "OCI_OBJECT_STORAGE": self = .ociObjectStorage
      case "ORACLE": self = .oracle
      case "AZURE_DATA_LAKE_STORAGE": self = .azureDataLakeStorage
      case "POSTGRESQL": self = .postgresql
      case "AZURE_SYNAPSE_ANALYTICS": self = .azureSynapseAnalytics
      case "SNOWFLAKE": self = .snowflake
      case "AMAZON_S3": self = .amazonS3
      case "HDFS": self = .hdfs
      case "ORACLE_AI_DATA_PLATFORM": self = .oracleAiDataPlatform
      case "ORACLE_NOSQL": self = .oracleNosql
      case "MONGODB": self = .mongodb
      case "AMAZON_KINESIS": self = .amazonKinesis
      case "AMAZON_REDSHIFT": self = .amazonRedshift
      case "DB2": self = .db2
      case "REDIS": self = .redis
      case "ELASTICSEARCH": self = .elasticsearch
      case "GENERIC": self = .generic
      case "GOOGLE_CLOUD_STORAGE": self = .googleCloudStorage
      case "GOOGLE_BIGQUERY": self = .googleBigquery
      case "DATABRICKS": self = .databricks
      case "GOOGLE_PUBSUB": self = .googlePubsub
      case "MICROSOFT_FABRIC": self = .microsoftFabric
      case "ICEBERG": self = .iceberg
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConnectionType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .goldengate
      case 2: self = .kafka
      case 3: self = .kafkaSchemaRegistry
      case 4: self = .mysql
      case 5: self = .javaMessageService
      case 6: self = .microsoftSqlserver
      case 7: self = .ociObjectStorage
      case 8: self = .oracle
      case 9: self = .azureDataLakeStorage
      case 10: self = .postgresql
      case 11: self = .azureSynapseAnalytics
      case 12: self = .snowflake
      case 13: self = .amazonS3
      case 14: self = .hdfs
      case 15: self = .oracleAiDataPlatform
      case 16: self = .oracleNosql
      case 17: self = .mongodb
      case 18: self = .amazonKinesis
      case 19: self = .amazonRedshift
      case 20: self = .db2
      case 21: self = .redis
      case 22: self = .elasticsearch
      case 23: self = .generic
      case 24: self = .googleCloudStorage
      case 25: self = .googleBigquery
      case 26: self = .databricks
      case 27: self = .googlePubsub
      case 28: self = .microsoftFabric
      case 29: self = .iceberg
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .goldengate: return try container.encode(1)
      case .kafka: return try container.encode(2)
      case .kafkaSchemaRegistry: return try container.encode(3)
      case .mysql: return try container.encode(4)
      case .javaMessageService: return try container.encode(5)
      case .microsoftSqlserver: return try container.encode(6)
      case .ociObjectStorage: return try container.encode(7)
      case .oracle: return try container.encode(8)
      case .azureDataLakeStorage: return try container.encode(9)
      case .postgresql: return try container.encode(10)
      case .azureSynapseAnalytics: return try container.encode(11)
      case .snowflake: return try container.encode(12)
      case .amazonS3: return try container.encode(13)
      case .hdfs: return try container.encode(14)
      case .oracleAiDataPlatform: return try container.encode(15)
      case .oracleNosql: return try container.encode(16)
      case .mongodb: return try container.encode(17)
      case .amazonKinesis: return try container.encode(18)
      case .amazonRedshift: return try container.encode(19)
      case .db2: return try container.encode(20)
      case .redis: return try container.encode(21)
      case .elasticsearch: return try container.encode(22)
      case .generic: return try container.encode(23)
      case .googleCloudStorage: return try container.encode(24)
      case .googleBigquery: return try container.encode(25)
      case .databricks: return try container.encode(26)
      case .googlePubsub: return try container.encode(27)
      case .microsoftFabric: return try container.encode(28)
      case .iceberg: return try container.encode(29)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.GoldengateConnectionType"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
