// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The properties of GoldengateMongodbConnection.
public struct GoldengateMongodbConnectionProperties: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// Optional. The technology type of MongodbConnection.
  public var technologyType: Swift.String = Swift.String()

  /// Optional. MongoDB connection string.
  /// e.g.: 'mongodb://mongodb0.example.com:27017/recordsrecords'
  public var connectionString: Swift.String = Swift.String()

  /// Optional. The username Oracle Goldengate uses to connect to the database.
  public var username: Swift.String = Swift.String()

  /// Optional. The OCID of the Oracle Autonomous Json Database.
  public var databaseId: Swift.String = Swift.String()

  /// Optional. Security Type for MongoDB.
  public var securityProtocol: GoldengateMongodbConnectionProperties.MongodbSecurityProtocol =
    GoldengateMongodbConnectionProperties.MongodbSecurityProtocol()

  /// Optional. Database Certificate - The base64 encoded content of a .pem file,
  /// containing the server public key (for 1 and 2-way SSL).
  public var tlsCaFile: Swift.String = Swift.String()

  /// Optional. Client Certificate - The base64 encoded content of a .pem file,
  /// containing the client public key (for 2-way SSL).
  public var tlsCertificateKeyFile: Swift.String = Swift.String()

  /// The password Oracle Goldengate uses to connect the associated database.
  public var connectionPasswordOptions: OneOf_ConnectionPasswordOptions? = nil

  /// Client Certificate key file password.
  public var tlsCertificateKeyFilePasswordOptions: OneOf_TlsCertificateKeyFilePasswordOptions? = nil

  /// Initialize a new instance of `GoldengateMongodbConnectionProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GoldengateMongodbConnectionProperties().with { $0.password = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case password = "password"
    case passwordSecretVersion = "passwordSecretVersion"
    case tlsCertificateKeyFilePassword = "tlsCertificateKeyFilePassword"
    case tlsCertificateKeyFilePasswordSecretVersion = "tlsCertificateKeyFilePasswordSecretVersion"
    case technologyType = "technologyType"
    case connectionString = "connectionString"
    case username = "username"
    case databaseId = "databaseId"
    case securityProtocol = "securityProtocol"
    case tlsCaFile = "tlsCaFile"
    case tlsCertificateKeyFile = "tlsCertificateKeyFile"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.technologyType = try container.decode(Swift.String.self, forKey: .technologyType)
    self.connectionString = try container.decode(Swift.String.self, forKey: .connectionString)
    self.username = try container.decode(Swift.String.self, forKey: .username)
    self.databaseId = try container.decode(Swift.String.self, forKey: .databaseId)
    self.securityProtocol = try container.decode(
      GoldengateMongodbConnectionProperties.MongodbSecurityProtocol.self, forKey: .securityProtocol)
    self.tlsCaFile = try container.decode(Swift.String.self, forKey: .tlsCaFile)
    self.tlsCertificateKeyFile = try container.decode(
      Swift.String.self, forKey: .tlsCertificateKeyFile)

    var connectionPasswordOptions: OneOf_ConnectionPasswordOptions? = nil
    let connectionPasswordOptionsCheckAndSet = {
      if connectionPasswordOptions != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'connectionPasswordOptions'"))
      }
      connectionPasswordOptions = $0
    }
    if let password = try container.decodeIfPresent(Swift.String.self, forKey: .password) {
      try connectionPasswordOptionsCheckAndSet(.password(password))
    }
    if let passwordSecretVersion = try container.decodeIfPresent(
      Swift.String.self, forKey: .passwordSecretVersion)
    {
      try connectionPasswordOptionsCheckAndSet(.passwordSecretVersion(passwordSecretVersion))
    }
    self.connectionPasswordOptions = connectionPasswordOptions

    var tlsCertificateKeyFilePasswordOptions: OneOf_TlsCertificateKeyFilePasswordOptions? = nil
    let tlsCertificateKeyFilePasswordOptionsCheckAndSet = {
      if tlsCertificateKeyFilePasswordOptions != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'tlsCertificateKeyFilePasswordOptions'"
          ))
      }
      tlsCertificateKeyFilePasswordOptions = $0
    }
    if let tlsCertificateKeyFilePassword = try container.decodeIfPresent(
      Swift.String.self, forKey: .tlsCertificateKeyFilePassword)
    {
      try tlsCertificateKeyFilePasswordOptionsCheckAndSet(
        .tlsCertificateKeyFilePassword(tlsCertificateKeyFilePassword))
    }
    if let tlsCertificateKeyFilePasswordSecretVersion = try container.decodeIfPresent(
      Swift.String.self, forKey: .tlsCertificateKeyFilePasswordSecretVersion)
    {
      try tlsCertificateKeyFilePasswordOptionsCheckAndSet(
        .tlsCertificateKeyFilePasswordSecretVersion(tlsCertificateKeyFilePasswordSecretVersion))
    }
    self.tlsCertificateKeyFilePasswordOptions = tlsCertificateKeyFilePasswordOptions
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.technologyType, forKey: .technologyType)
    try container.encode(self.connectionString, forKey: .connectionString)
    try container.encode(self.username, forKey: .username)
    try container.encode(self.databaseId, forKey: .databaseId)
    try container.encode(self.securityProtocol, forKey: .securityProtocol)
    try container.encode(self.tlsCaFile, forKey: .tlsCaFile)
    try container.encode(self.tlsCertificateKeyFile, forKey: .tlsCertificateKeyFile)

    if let choice = self.connectionPasswordOptions {
      switch choice {
      case .password(let value):
        try container.encode(value, forKey: .password)
      case .passwordSecretVersion(let value):
        try container.encode(value, forKey: .passwordSecretVersion)
      }
    }

    if let choice = self.tlsCertificateKeyFilePasswordOptions {
      switch choice {
      case .tlsCertificateKeyFilePassword(let value):
        try container.encode(value, forKey: .tlsCertificateKeyFilePassword)
      case .tlsCertificateKeyFilePasswordSecretVersion(let value):
        try container.encode(value, forKey: .tlsCertificateKeyFilePasswordSecretVersion)
      }
    }
  }

  /// Enum for Security Type for MongoDB.
  public enum MongodbSecurityProtocol: Codable, Equatable, Sendable {
    /// Security type not specified.
    case unspecified
    /// Plain text communication.
    case plain
    /// Transport Layer Security.
    case tls
    /// Mutual Transport Layer Security.
    case mtls
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .plain: return 1
      case .tls: return 2
      case .mtls: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MONGODB_SECURITY_PROTOCOL_UNSPECIFIED"
      case .plain: return "PLAIN"
      case .tls: return "TLS"
      case .mtls: return "MTLS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:MongodbSecurityProtocol/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MONGODB_SECURITY_PROTOCOL_UNSPECIFIED": self = .unspecified
      case "PLAIN": self = .plain
      case "TLS": self = .tls
      case "MTLS": self = .mtls
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:MongodbSecurityProtocol/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .plain
      case 2: self = .tls
      case 3: self = .mtls
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .plain: return try container.encode(1)
      case .tls: return try container.encode(2)
      case .mtls: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The password Oracle Goldengate uses to connect the associated database.
  public enum OneOf_ConnectionPasswordOptions: Codable, Equatable, Sendable {
    /// Optional. Input only. The password Oracle Goldengate uses to connect the
    /// Mongodb connection in plain text.
    case password(Swift.String)
    /// Optional. Input only. The resource name of a secret version in Secret
    /// Manager which contains the password Oracle Goldengate uses to connect the
    /// Mongodb connection. Format:
    /// projects/{project}/secrets/{secret}/versions/{version}.
    case passwordSecretVersion(Swift.String)
  }

  /// Client Certificate key file password.
  public enum OneOf_TlsCertificateKeyFilePasswordOptions: Codable, Equatable, Sendable {
    /// Optional. Input only. The Client Certificate key file password in plain
    /// text.
    case tlsCertificateKeyFilePassword(Swift.String)
    /// Optional. Input only. The resource name of a secret version in Secret
    /// Manager which contains the Client Certificate key file password in Secret
    /// Manager. Format: projects/{project}/secrets/{secret}/versions/{version}.
    case tlsCertificateKeyFilePasswordSecretVersion(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.oracledatabase.v1.GoldengateMongodbConnectionProperties"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
