// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The properties of a GoldengateConnectionAssignment.
public struct GoldengateConnectionAssignmentProperties: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The
  /// [OCID](https://docs.cloud.oracle.com/Content/General/Concepts/identifiers.htm)
  /// of the connection assignment being referenced.
  public var ocid: Swift.String = Swift.String()

  /// Required. The GoldengateConnection resource to be assigned.
  /// Format:
  /// projects/{project}/locations/{location}/goldengateConnections/{goldengate_connection}
  public var goldengateConnection: Swift.String = Swift.String()

  /// Required. The GoldenGateDeployment to assign the connection to.
  /// Format:
  /// projects/{project}/locations/{location}/goldengateDeployments/{goldengate_deployment}
  public var goldengateDeployment: Swift.String = Swift.String()

  /// Output only. Credential store alias.
  public var alias: Swift.String = Swift.String()

  /// Output only. The lifecycle state of the connection assignment.
  public var state: GoldengateConnectionAssignmentProperties.State =
    GoldengateConnectionAssignmentProperties.State()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GoldengateConnectionAssignmentProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GoldengateConnectionAssignmentProperties().with { $0.ocid = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let ocid = CodingKeys(stringValue: "ocid")
    static let goldengateConnection = CodingKeys(stringValue: "goldengateConnection")
    static let goldengateDeployment = CodingKeys(stringValue: "goldengateDeployment")
    static let alias = CodingKeys(stringValue: "alias")
    static let state = CodingKeys(stringValue: "state")

    static let _knownKeys: Set<Swift.String> = [
      "ocid",
      "goldengateConnection",
      "goldengateDeployment",
      "alias",
      "state",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ocid) {
      self.ocid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .goldengateConnection) {
      self.goldengateConnection = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .goldengateDeployment) {
      self.goldengateDeployment = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .alias) {
      self.alias = value
    }
    if let value = try container.decodeIfPresent(
      GoldengateConnectionAssignmentProperties.State.self, forKey: .state)
    {
      self.state = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.ocid, forKey: .ocid)
    try container.encode(self.goldengateConnection, forKey: .goldengateConnection)
    try container.encode(self.goldengateDeployment, forKey: .goldengateDeployment)
    try container.encode(self.alias, forKey: .alias)
    try container.encode(self.state, forKey: .state)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Possible lifecycle states for connection assignments.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// Lifecycle state is unspecified.
    case unspecified
    /// Connection assignment is being created.
    case creating
    /// Connection assignment is active.
    case active
    /// Connection assignment failed.
    case failed
    /// Connection assignment is being updated.
    case updating
    /// Connection assignment is being deleted.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .failed: return 3
      case .updating: return 4
      case .deleting: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .failed: return "FAILED"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "FAILED": self = .failed
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .failed
      case 4: self = .updating
      case 5: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .active: return try container.encode("ACTIVE")
      case .failed: return try container.encode("FAILED")
      case .updating: return try container.encode("UPDATING")
      case .deleting: return try container.encode("DELETING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.oracledatabase.v1.GoldengateConnectionAssignmentProperties"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
