// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The properties of GoldengateKafkaConnection.
public struct GoldengateKafkaConnectionProperties: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. The technology type of KafkaConnection.
  public var technologyType: Swift.String = Swift.String()

  /// Optional. The OCID of the stream pool being referenced.
  public var streamPoolId: Swift.String = Swift.String()

  /// Optional. The OCID of the Kafka cluster being referenced from OCI Streaming
  /// with Apache Kafka.
  public var clusterId: Swift.String = Swift.String()

  /// Optional. Kafka bootstrap. Equivalent of bootstrap.servers configuration
  /// property in Kafka: list of KafkaBootstrapServer objects specified by
  /// host/port. Used for establishing the initial connection to the Kafka
  /// cluster. Example: "server1.example.com:9092,server2.example.com:9092"
  public var bootstrapServers: [KafkaBootstrapServer] = []

  /// Optional. Security Type for Kafka.
  public var securityProtocol: GoldengateKafkaConnectionProperties.KafkaSecurityProtocol =
    GoldengateKafkaConnectionProperties.KafkaSecurityProtocol()

  /// Optional. The username Oracle Goldengate uses to connect the associated
  /// system of the given technology.
  public var username: Swift.String = Swift.String()

  /// Optional. The base64 encoded content of the TrustStore file.
  public var trustStoreFile: Swift.String = Swift.String()

  /// Optional. The base64 encoded content of the KeyStore file.
  public var keyStoreFile: Swift.String = Swift.String()

  /// Optional. The base64 encoded content of the consumer.properties file.
  public var consumerPropertiesFile: Swift.String = Swift.String()

  /// Optional. The base64 encoded content of the producer.properties file.
  public var producerPropertiesFile: Swift.String = Swift.String()

  /// Optional. Specifies that the user intends to authenticate to the instance
  /// using a resource principal. Applicable only for OCI Streaming connections.
  public var useResourcePrincipal: Swift.Bool = Swift.Bool()

  /// The password for Kafka basic/SASL auth.
  public var connectionPasswordOptions: OneOf_ConnectionPasswordOptions? = nil

  /// The TrustStore password.
  public var trustStorePasswordOptions: OneOf_TrustStorePasswordOptions? = nil

  /// The KeyStore password.
  public var keyStorePasswordOptions: OneOf_KeyStorePasswordOptions? = nil

  /// The password for the cert inside of the KeyStore.
  /// In case it differs from the KeyStore password, it should be provided.
  public var sslKeyPasswordOptions: OneOf_SslKeyPasswordOptions? = nil

  /// Initialize a new instance of `GoldengateKafkaConnectionProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GoldengateKafkaConnectionProperties().with { $0.password = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case password = "password"
    case passwordSecretVersion = "passwordSecretVersion"
    case trustStorePassword = "trustStorePassword"
    case trustStorePasswordSecretVersion = "trustStorePasswordSecretVersion"
    case keyStorePassword = "keyStorePassword"
    case keyStorePasswordSecretVersion = "keyStorePasswordSecretVersion"
    case sslKeyPassword = "sslKeyPassword"
    case sslKeyPasswordSecretVersion = "sslKeyPasswordSecretVersion"
    case technologyType = "technologyType"
    case streamPoolId = "streamPoolId"
    case clusterId = "clusterId"
    case bootstrapServers = "bootstrapServers"
    case securityProtocol = "securityProtocol"
    case username = "username"
    case trustStoreFile = "trustStoreFile"
    case keyStoreFile = "keyStoreFile"
    case consumerPropertiesFile = "consumerPropertiesFile"
    case producerPropertiesFile = "producerPropertiesFile"
    case useResourcePrincipal = "useResourcePrincipal"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.technologyType = try container.decode(Swift.String.self, forKey: .technologyType)
    self.streamPoolId = try container.decode(Swift.String.self, forKey: .streamPoolId)
    self.clusterId = try container.decode(Swift.String.self, forKey: .clusterId)
    self.bootstrapServers = try container.decode(
      [KafkaBootstrapServer].self, forKey: .bootstrapServers)
    self.securityProtocol = try container.decode(
      GoldengateKafkaConnectionProperties.KafkaSecurityProtocol.self, forKey: .securityProtocol)
    self.username = try container.decode(Swift.String.self, forKey: .username)
    self.trustStoreFile = try container.decode(Swift.String.self, forKey: .trustStoreFile)
    self.keyStoreFile = try container.decode(Swift.String.self, forKey: .keyStoreFile)
    self.consumerPropertiesFile = try container.decode(
      Swift.String.self, forKey: .consumerPropertiesFile)
    self.producerPropertiesFile = try container.decode(
      Swift.String.self, forKey: .producerPropertiesFile)
    self.useResourcePrincipal = try container.decode(Swift.Bool.self, forKey: .useResourcePrincipal)

    var connectionPasswordOptions: OneOf_ConnectionPasswordOptions? = nil
    let connectionPasswordOptionsCheckAndSet = {
      if connectionPasswordOptions != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'connectionPasswordOptions'"))
      }
      connectionPasswordOptions = $0
    }
    if let password = try container.decodeIfPresent(Swift.String.self, forKey: .password) {
      try connectionPasswordOptionsCheckAndSet(.password(password))
    }
    if let passwordSecretVersion = try container.decodeIfPresent(
      Swift.String.self, forKey: .passwordSecretVersion)
    {
      try connectionPasswordOptionsCheckAndSet(.passwordSecretVersion(passwordSecretVersion))
    }
    self.connectionPasswordOptions = connectionPasswordOptions

    var trustStorePasswordOptions: OneOf_TrustStorePasswordOptions? = nil
    let trustStorePasswordOptionsCheckAndSet = {
      if trustStorePasswordOptions != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'trustStorePasswordOptions'"))
      }
      trustStorePasswordOptions = $0
    }
    if let trustStorePassword = try container.decodeIfPresent(
      Swift.String.self, forKey: .trustStorePassword)
    {
      try trustStorePasswordOptionsCheckAndSet(.trustStorePassword(trustStorePassword))
    }
    if let trustStorePasswordSecretVersion = try container.decodeIfPresent(
      Swift.String.self, forKey: .trustStorePasswordSecretVersion)
    {
      try trustStorePasswordOptionsCheckAndSet(
        .trustStorePasswordSecretVersion(trustStorePasswordSecretVersion))
    }
    self.trustStorePasswordOptions = trustStorePasswordOptions

    var keyStorePasswordOptions: OneOf_KeyStorePasswordOptions? = nil
    let keyStorePasswordOptionsCheckAndSet = {
      if keyStorePasswordOptions != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'keyStorePasswordOptions'"))
      }
      keyStorePasswordOptions = $0
    }
    if let keyStorePassword = try container.decodeIfPresent(
      Swift.String.self, forKey: .keyStorePassword)
    {
      try keyStorePasswordOptionsCheckAndSet(.keyStorePassword(keyStorePassword))
    }
    if let keyStorePasswordSecretVersion = try container.decodeIfPresent(
      Swift.String.self, forKey: .keyStorePasswordSecretVersion)
    {
      try keyStorePasswordOptionsCheckAndSet(
        .keyStorePasswordSecretVersion(keyStorePasswordSecretVersion))
    }
    self.keyStorePasswordOptions = keyStorePasswordOptions

    var sslKeyPasswordOptions: OneOf_SslKeyPasswordOptions? = nil
    let sslKeyPasswordOptionsCheckAndSet = {
      if sslKeyPasswordOptions != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'sslKeyPasswordOptions'"))
      }
      sslKeyPasswordOptions = $0
    }
    if let sslKeyPassword = try container.decodeIfPresent(
      Swift.String.self, forKey: .sslKeyPassword)
    {
      try sslKeyPasswordOptionsCheckAndSet(.sslKeyPassword(sslKeyPassword))
    }
    if let sslKeyPasswordSecretVersion = try container.decodeIfPresent(
      Swift.String.self, forKey: .sslKeyPasswordSecretVersion)
    {
      try sslKeyPasswordOptionsCheckAndSet(
        .sslKeyPasswordSecretVersion(sslKeyPasswordSecretVersion))
    }
    self.sslKeyPasswordOptions = sslKeyPasswordOptions
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.technologyType, forKey: .technologyType)
    try container.encode(self.streamPoolId, forKey: .streamPoolId)
    try container.encode(self.clusterId, forKey: .clusterId)
    try container.encode(self.bootstrapServers, forKey: .bootstrapServers)
    try container.encode(self.securityProtocol, forKey: .securityProtocol)
    try container.encode(self.username, forKey: .username)
    try container.encode(self.trustStoreFile, forKey: .trustStoreFile)
    try container.encode(self.keyStoreFile, forKey: .keyStoreFile)
    try container.encode(self.consumerPropertiesFile, forKey: .consumerPropertiesFile)
    try container.encode(self.producerPropertiesFile, forKey: .producerPropertiesFile)
    try container.encode(self.useResourcePrincipal, forKey: .useResourcePrincipal)

    if let choice = self.connectionPasswordOptions {
      switch choice {
      case .password(let value):
        try container.encode(value, forKey: .password)
      case .passwordSecretVersion(let value):
        try container.encode(value, forKey: .passwordSecretVersion)
      }
    }

    if let choice = self.trustStorePasswordOptions {
      switch choice {
      case .trustStorePassword(let value):
        try container.encode(value, forKey: .trustStorePassword)
      case .trustStorePasswordSecretVersion(let value):
        try container.encode(value, forKey: .trustStorePasswordSecretVersion)
      }
    }

    if let choice = self.keyStorePasswordOptions {
      switch choice {
      case .keyStorePassword(let value):
        try container.encode(value, forKey: .keyStorePassword)
      case .keyStorePasswordSecretVersion(let value):
        try container.encode(value, forKey: .keyStorePasswordSecretVersion)
      }
    }

    if let choice = self.sslKeyPasswordOptions {
      switch choice {
      case .sslKeyPassword(let value):
        try container.encode(value, forKey: .sslKeyPassword)
      case .sslKeyPasswordSecretVersion(let value):
        try container.encode(value, forKey: .sslKeyPasswordSecretVersion)
      }
    }
  }

  /// Enum for Security Type for Kafka.
  public enum KafkaSecurityProtocol: Codable, Equatable, Sendable {
    /// Security type not specified.
    case unspecified
    /// SSL security protocol.
    case ssl
    /// SASL SSL security protocol.
    case saslSsl
    /// Plaintext security protocol.
    case plaintext
    /// SASL Plaintext security protocol.
    case saslPlaintext
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ssl: return 1
      case .saslSsl: return 2
      case .plaintext: return 3
      case .saslPlaintext: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "KAFKA_SECURITY_PROTOCOL_UNSPECIFIED"
      case .ssl: return "SSL"
      case .saslSsl: return "SASL_SSL"
      case .plaintext: return "PLAINTEXT"
      case .saslPlaintext: return "SASL_PLAINTEXT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:KafkaSecurityProtocol/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "KAFKA_SECURITY_PROTOCOL_UNSPECIFIED": self = .unspecified
      case "SSL": self = .ssl
      case "SASL_SSL": self = .saslSsl
      case "PLAINTEXT": self = .plaintext
      case "SASL_PLAINTEXT": self = .saslPlaintext
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:KafkaSecurityProtocol/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ssl
      case 2: self = .saslSsl
      case 3: self = .plaintext
      case 4: self = .saslPlaintext
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .ssl: return try container.encode(1)
      case .saslSsl: return try container.encode(2)
      case .plaintext: return try container.encode(3)
      case .saslPlaintext: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The password for Kafka basic/SASL auth.
  public enum OneOf_ConnectionPasswordOptions: Codable, Equatable, Sendable {
    /// Optional. Input only. The password for Kafka basic/SASL auth in plain
    /// text.
    case password(Swift.String)
    /// Optional. Input only. The resource name of a secret version in Secret
    /// Manager which contains the password for Kafka basic/SASL auth. Format:
    /// projects/{project}/secrets/{secret}/versions/{version}.
    case passwordSecretVersion(Swift.String)
  }

  /// The TrustStore password.
  public enum OneOf_TrustStorePasswordOptions: Codable, Equatable, Sendable {
    /// Optional. Input only. The TrustStore password in plain text.
    case trustStorePassword(Swift.String)
    /// Optional. Input only. The resource name of a secret version in Secret
    /// Manager which contains the TrustStore password. Format:
    /// projects/{project}/secrets/{secret}/versions/{version}.
    case trustStorePasswordSecretVersion(Swift.String)
  }

  /// The KeyStore password.
  public enum OneOf_KeyStorePasswordOptions: Codable, Equatable, Sendable {
    /// Optional. Input only. The KeyStore password in plain text.
    case keyStorePassword(Swift.String)
    /// Optional. Input only. The resource name of a secret version in Secret
    /// Manager which contains the KeyStore password. Format:
    /// projects/{project}/secrets/{secret}/versions/{version}.
    case keyStorePasswordSecretVersion(Swift.String)
  }

  /// The password for the cert inside of the KeyStore.
  /// In case it differs from the KeyStore password, it should be provided.
  public enum OneOf_SslKeyPasswordOptions: Codable, Equatable, Sendable {
    /// Optional. Input only. The password for the cert inside of the KeyStore in
    /// plain text.
    case sslKeyPassword(Swift.String)
    /// Optional. Input only. The resource name of a secret version in Secret
    /// Manager which contains the password for the cert inside of the KeyStore.
    /// Format: projects/{project}/secrets/{secret}/versions/{version}.
    case sslKeyPasswordSecretVersion(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.GoldengateKafkaConnectionProperties"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
