// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The properties of Goldengate Oracle Database Connection.
public struct GoldengateOracleConnectionProperties: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The technology type.
  public var technologyType: Swift.String = Swift.String()

  /// Optional. The username Oracle Goldengate uses to connect.
  public var username: Swift.String = Swift.String()

  /// Optional. Authentication mode.
  public var authenticationMode: GoldengateOracleConnectionProperties.OracleAuthenticationMode =
    GoldengateOracleConnectionProperties.OracleAuthenticationMode()

  /// Optional. Connect descriptor or Easy Connect Naming method used to connect
  /// to a database.
  public var connectionString: Swift.String = Swift.String()

  /// Optional. The mode of the database connection session to be established by
  /// the data client.
  public var sessionMode: GoldengateOracleConnectionProperties.SessionMode =
    GoldengateOracleConnectionProperties.SessionMode()

  /// Optional. Autonomous AI Database instance id of database in Oracle Database
  /// @ Google Cloud. If gcp_oracle_database_id is provided, connection_string
  /// must be empty. Format:
  /// projects/{project}/locations/{location}/autonomousDatabases/{autonomous_database}
  public var gcpOracleDatabaseId: Swift.String = Swift.String()

  /// Optional. The wallet contents Oracle Goldengate uses to make connections to
  /// a database. This attribute is expected to be base64 encoded.
  public var walletFile: Swift.String = Swift.String()

  /// The password Oracle Goldengate uses to connect the associated system of the
  /// given technology. It must conform to the specific security requirements
  /// including length, case sensitivity, and so on.
  public var connectionPasswordOptions: OneOf_ConnectionPasswordOptions? = nil

  /// Initialize a new instance of `GoldengateOracleConnectionProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GoldengateOracleConnectionProperties().with { $0.password = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case password = "password"
    case passwordSecretVersion = "passwordSecretVersion"
    case technologyType = "technologyType"
    case username = "username"
    case authenticationMode = "authenticationMode"
    case connectionString = "connectionString"
    case sessionMode = "sessionMode"
    case gcpOracleDatabaseId = "gcpOracleDatabaseId"
    case walletFile = "walletFile"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.technologyType = try container.decode(Swift.String.self, forKey: .technologyType)
    self.username = try container.decode(Swift.String.self, forKey: .username)
    self.authenticationMode = try container.decode(
      GoldengateOracleConnectionProperties.OracleAuthenticationMode.self,
      forKey: .authenticationMode)
    self.connectionString = try container.decode(Swift.String.self, forKey: .connectionString)
    self.sessionMode = try container.decode(
      GoldengateOracleConnectionProperties.SessionMode.self, forKey: .sessionMode)
    self.gcpOracleDatabaseId = try container.decode(Swift.String.self, forKey: .gcpOracleDatabaseId)
    self.walletFile = try container.decode(Swift.String.self, forKey: .walletFile)

    var connectionPasswordOptions: OneOf_ConnectionPasswordOptions? = nil
    let connectionPasswordOptionsCheckAndSet = {
      if connectionPasswordOptions != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'connectionPasswordOptions'"))
      }
      connectionPasswordOptions = $0
    }
    if let password = try container.decodeIfPresent(Swift.String.self, forKey: .password) {
      try connectionPasswordOptionsCheckAndSet(.password(password))
    }
    if let passwordSecretVersion = try container.decodeIfPresent(
      Swift.String.self, forKey: .passwordSecretVersion)
    {
      try connectionPasswordOptionsCheckAndSet(.passwordSecretVersion(passwordSecretVersion))
    }
    self.connectionPasswordOptions = connectionPasswordOptions
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.technologyType, forKey: .technologyType)
    try container.encode(self.username, forKey: .username)
    try container.encode(self.authenticationMode, forKey: .authenticationMode)
    try container.encode(self.connectionString, forKey: .connectionString)
    try container.encode(self.sessionMode, forKey: .sessionMode)
    try container.encode(self.gcpOracleDatabaseId, forKey: .gcpOracleDatabaseId)
    try container.encode(self.walletFile, forKey: .walletFile)

    if let choice = self.connectionPasswordOptions {
      switch choice {
      case .password(let value):
        try container.encode(value, forKey: .password)
      case .passwordSecretVersion(let value):
        try container.encode(value, forKey: .passwordSecretVersion)
      }
    }
  }

  /// Enum for Authentication mode.
  public enum OracleAuthenticationMode: Codable, Equatable, Sendable {
    /// Authentication mode not specified.
    case unspecified
    /// TLS authentication mode.
    case tls
    /// MTLS authentication mode.
    case mtls
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .tls: return 1
      case .mtls: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ORACLE_AUTHENTICATION_MODE_UNSPECIFIED"
      case .tls: return "TLS"
      case .mtls: return "MTLS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OracleAuthenticationMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ORACLE_AUTHENTICATION_MODE_UNSPECIFIED": self = .unspecified
      case "TLS": self = .tls
      case "MTLS": self = .mtls
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OracleAuthenticationMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .tls
      case 2: self = .mtls
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .tls: return try container.encode(1)
      case .mtls: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The various session modes of the GoldengateConnection.
  public enum SessionMode: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Indicates that the resource is using direct session mode.
    case direct
    /// Indicates that the resource is using redirect session mode.
    case redirect
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .direct: return 1
      case .redirect: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SESSION_MODE_UNSPECIFIED"
      case .direct: return "DIRECT"
      case .redirect: return "REDIRECT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SessionMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SESSION_MODE_UNSPECIFIED": self = .unspecified
      case "DIRECT": self = .direct
      case "REDIRECT": self = .redirect
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SessionMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .direct
      case 2: self = .redirect
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .direct: return try container.encode(1)
      case .redirect: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The password Oracle Goldengate uses to connect the associated system of the
  /// given technology. It must conform to the specific security requirements
  /// including length, case sensitivity, and so on.
  public enum OneOf_ConnectionPasswordOptions: Codable, Equatable, Sendable {
    /// Optional. Input only. The password Oracle Goldengate uses in plain text.
    case password(Swift.String)
    /// Optional. Input only. The resource name of a secret version in Secret
    /// Manager which contains the password Oracle Goldengate uses. Format:
    /// projects/{project}/secrets/{secret}/versions/{version}.
    case passwordSecretVersion(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.GoldengateOracleConnectionProperties"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
