// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The properties of GoldengateAzureDataLakeStorageConnection.
public struct GoldengateAzureDataLakeStorageConnectionProperties: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// Optional. The technology type of AzureDataLakeStorageConnection.
  public var technologyType: Swift.String = Swift.String()

  /// Optional. Authentication mechanism to access Azure Data Lake Storage.
  public var authenticationType:
    GoldengateAzureDataLakeStorageConnectionProperties.AuthenticationType =
      GoldengateAzureDataLakeStorageConnectionProperties.AuthenticationType()

  /// Optional. Sets the Azure storage account name.
  public var account: Swift.String = Swift.String()

  /// Optional. Azure storage account key. This property is required when
  /// 'authentication_type' is set to 'SHARED_KEY'.
  public var accountKeySecret: Swift.String = Swift.String()

  /// Optional. Credential that uses a shared access signature (SAS) to
  /// authenticate to an Azure Service.
  public var sasTokenSecret: Swift.String = Swift.String()

  /// Optional. Azure tenant ID of the application. This property is required
  /// when 'authentication_type' is set to 'AZURE_ACTIVE_DIRECTORY'.
  public var azureTenantId: Swift.String = Swift.String()

  /// Optional. Azure client ID of the application. This property is required
  /// when 'authentication_type' is set to 'AZURE_ACTIVE_DIRECTORY'.
  public var clientId: Swift.String = Swift.String()

  /// Optional. Azure client secret (aka application password) for
  /// authentication.
  public var clientSecret: Swift.String = Swift.String()

  /// Optional. Azure Storage service endpoint.
  /// e.g: https://test.blob.core.windows.net
  public var endpoint: Swift.String = Swift.String()

  /// Optional. The endpoint used for authentication with Microsoft Entra ID
  /// (formerly Azure Active Directory). Default value:
  /// https://login.microsoftonline.com
  public var azureAuthorityHost: Swift.String = Swift.String()

  /// Initialize a new instance of `GoldengateAzureDataLakeStorageConnectionProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GoldengateAzureDataLakeStorageConnectionProperties().with { $0.technologyType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Enum for authentication mechanism to access Azure Data Lake Storage.
  public enum AuthenticationType: Codable, Equatable, Sendable {
    /// Authentication type not specified.
    case unspecified
    /// Shared key authentication.
    case sharedKey
    /// Shared access signature authentication.
    case sharedAccessSignature
    /// Azure active directory authentication.
    case azureActiveDirectory
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .sharedKey: return 1
      case .sharedAccessSignature: return 2
      case .azureActiveDirectory: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "AUTHENTICATION_TYPE_UNSPECIFIED"
      case .sharedKey: return "SHARED_KEY"
      case .sharedAccessSignature: return "SHARED_ACCESS_SIGNATURE"
      case .azureActiveDirectory: return "AZURE_ACTIVE_DIRECTORY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AuthenticationType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "AUTHENTICATION_TYPE_UNSPECIFIED": self = .unspecified
      case "SHARED_KEY": self = .sharedKey
      case "SHARED_ACCESS_SIGNATURE": self = .sharedAccessSignature
      case "AZURE_ACTIVE_DIRECTORY": self = .azureActiveDirectory
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AuthenticationType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .sharedKey
      case 2: self = .sharedAccessSignature
      case 3: self = .azureActiveDirectory
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .sharedKey: return try container.encode(1)
      case .sharedAccessSignature: return try container.encode(2)
      case .azureActiveDirectory: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.oracledatabase.v1.GoldengateAzureDataLakeStorageConnectionProperties"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
