// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The properties of GoldengateOracleNosqlConnection.
public struct GoldengateOracleNosqlConnectionProperties: Codable, Equatable, GoogleCloudWKT
    ._AnyPackable,
  Sendable
{
  /// Optional. The technology type of OracleNosqlConnection.
  public var technologyType: Swift.String = Swift.String()

  /// Optional. The OCID of the OCI tenancy.
  public var tenancyId: Swift.String = Swift.String()

  /// Optional. The name of the region. e.g.: us-ashburn-1
  public var region: Swift.String = Swift.String()

  /// Optional. The OCID of the OCI user who will access the Oracle NoSQL
  /// database.
  public var userId: Swift.String = Swift.String()

  /// Optional. The content of the private key file (PEM file)
  /// corresponding to the API key of the fingerprint.
  public var privateKeyFile: Swift.String = Swift.String()

  /// Optional. The passphrase of the private key.
  public var privateKeyPassphraseSecret: Swift.String = Swift.String()

  /// Optional. The fingerprint of the API Key of the user specified by the
  /// userId.
  public var publicKeyFingerprint: Swift.String = Swift.String()

  /// Optional. Specifies that the user intends to authenticate to the instance
  /// using a resource principal.
  public var useResourcePrincipal: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `GoldengateOracleNosqlConnectionProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GoldengateOracleNosqlConnectionProperties().with { $0.technologyType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.oracledatabase.v1.GoldengateOracleNosqlConnectionProperties"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
