// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Details of the Goldengate Deployment Type resource.
public struct GoldengateDeploymentType: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The name of the Goldengate Deployment Type resource with the
  /// format:
  /// projects/{project}/locations/{region}/goldengateDeploymentTypes/{goldengate_deployment_type}
  public var name: Swift.String = Swift.String()

  /// Output only. The deployment type of the Goldengate Deployment Type
  /// resource.
  public var deploymentType: GoldengateDeploymentType.DeploymentType =
    GoldengateDeploymentType.DeploymentType()

  /// Output only. The category of the Goldengate Deployment Type resource.
  public var category: GoldengateDeploymentType.DeploymentCategory =
    GoldengateDeploymentType.DeploymentCategory()

  /// Output only. The connection types of the Goldengate Deployment Type
  /// resource.
  public var connectionTypes: [Swift.String] = []

  /// Output only. The display name of the Goldengate Deployment Type resource.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The Ogg version of the Goldengate Deployment Type resource.
  public var oggVersion: Swift.String = Swift.String()

  /// Output only. The source technologies of the Goldengate Deployment Type
  /// resource.
  public var sourceTechnologies: [Swift.String] = []

  /// Output only. The supported capabilities of the Goldengate Deployment Type
  /// resource.
  public var supportedCapabilities: [Swift.String] = []

  /// Output only. The supported technologies URL of the Goldengate Deployment
  /// Type resource.
  public var supportedTechnologiesUrl: Swift.String = Swift.String()

  /// Output only. The target technologies of the Goldengate Deployment Type
  /// resource.
  public var targetTechnologies: [Swift.String] = []

  /// Output only. The default username of the Goldengate Deployment Type
  /// resource.
  public var defaultUsername: Swift.String = Swift.String()

  /// Initialize a new instance of `GoldengateDeploymentType`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GoldengateDeploymentType().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The deployment type of the Goldengate Deployment Type resource.
  public enum DeploymentType: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Goldengate Deployment Type category is OGG.
    case ogg
    /// Goldengate Deployment Type category is DATABASE_ORACLE.
    case databaseOracle
    /// Goldengate Deployment Type category is BIGDATA.
    case bigdata
    /// Goldengate Deployment Type category is DATABASE_MICROSOFT_SQLSERVER.
    case databaseMicrosoftSqlserver
    /// Goldengate Deployment Type category is DATABASE_MYSQL.
    case databaseMysql
    /// Goldengate Deployment Type category is DATABASE_POSTGRESQL.
    case databasePostgresql
    /// Goldengate Deployment Type category is DATABASE_DB2ZOS.
    case databaseDb2Zos
    /// Goldengate Deployment Type category is DATABASE_DB2I.
    case databaseDb2I
    /// Goldengate Deployment Type category is GGSA.
    case ggsa
    /// Goldengate Deployment Type category is DATA_TRANSFORMS.
    case dataTransforms
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ogg: return 1
      case .databaseOracle: return 2
      case .bigdata: return 3
      case .databaseMicrosoftSqlserver: return 4
      case .databaseMysql: return 5
      case .databasePostgresql: return 6
      case .databaseDb2Zos: return 7
      case .databaseDb2I: return 8
      case .ggsa: return 9
      case .dataTransforms: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DEPLOYMENT_TYPE_UNSPECIFIED"
      case .ogg: return "OGG"
      case .databaseOracle: return "DATABASE_ORACLE"
      case .bigdata: return "BIGDATA"
      case .databaseMicrosoftSqlserver: return "DATABASE_MICROSOFT_SQLSERVER"
      case .databaseMysql: return "DATABASE_MYSQL"
      case .databasePostgresql: return "DATABASE_POSTGRESQL"
      case .databaseDb2Zos: return "DATABASE_DB2ZOS"
      case .databaseDb2I: return "DATABASE_DB2I"
      case .ggsa: return "GGSA"
      case .dataTransforms: return "DATA_TRANSFORMS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DeploymentType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DEPLOYMENT_TYPE_UNSPECIFIED": self = .unspecified
      case "OGG": self = .ogg
      case "DATABASE_ORACLE": self = .databaseOracle
      case "BIGDATA": self = .bigdata
      case "DATABASE_MICROSOFT_SQLSERVER": self = .databaseMicrosoftSqlserver
      case "DATABASE_MYSQL": self = .databaseMysql
      case "DATABASE_POSTGRESQL": self = .databasePostgresql
      case "DATABASE_DB2ZOS": self = .databaseDb2Zos
      case "DATABASE_DB2I": self = .databaseDb2I
      case "GGSA": self = .ggsa
      case "DATA_TRANSFORMS": self = .dataTransforms
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DeploymentType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ogg
      case 2: self = .databaseOracle
      case 3: self = .bigdata
      case 4: self = .databaseMicrosoftSqlserver
      case 5: self = .databaseMysql
      case 6: self = .databasePostgresql
      case 7: self = .databaseDb2Zos
      case 8: self = .databaseDb2I
      case 9: self = .ggsa
      case 10: self = .dataTransforms
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .ogg: return try container.encode(1)
      case .databaseOracle: return try container.encode(2)
      case .bigdata: return try container.encode(3)
      case .databaseMicrosoftSqlserver: return try container.encode(4)
      case .databaseMysql: return try container.encode(5)
      case .databasePostgresql: return try container.encode(6)
      case .databaseDb2Zos: return try container.encode(7)
      case .databaseDb2I: return try container.encode(8)
      case .ggsa: return try container.encode(9)
      case .dataTransforms: return try container.encode(10)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The category of the Goldengate Deployment Type resource.
  public enum DeploymentCategory: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// Goldengate Deployment Type category is DATA_REPLICATION_CATEGORY.
    case dataReplicationCategory
    /// Goldengate Deployment Type category is DATA_TRANSFORMS_CATEGORY.
    case dataTransformsCategory
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .dataReplicationCategory: return 1
      case .dataTransformsCategory: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DEPLOYMENT_CATEGORY_UNSPECIFIED"
      case .dataReplicationCategory: return "DATA_REPLICATION_CATEGORY"
      case .dataTransformsCategory: return "DATA_TRANSFORMS_CATEGORY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DeploymentCategory/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DEPLOYMENT_CATEGORY_UNSPECIFIED": self = .unspecified
      case "DATA_REPLICATION_CATEGORY": self = .dataReplicationCategory
      case "DATA_TRANSFORMS_CATEGORY": self = .dataTransformsCategory
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DeploymentCategory/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .dataReplicationCategory
      case 2: self = .dataTransformsCategory
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .dataReplicationCategory: return try container.encode(1)
      case .dataTransformsCategory: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.GoldengateDeploymentType"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
