// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The identity connector details which will allow OCI to securely access
/// the resources in the customer project.
public struct IdentityConnector: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. A google managed service account on which customers can grant
  /// roles to access resources in the customer project. Example:
  /// `p176944527254-55-75119d87fd8f@gcp-sa-oci.iam.gserviceaccount.com`
  public var serviceAgentEmail: Swift.String = Swift.String()

  /// Output only. The connection state of the identity connector.
  public var connectionState: IdentityConnector.ConnectionState =
    IdentityConnector.ConnectionState()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `IdentityConnector`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IdentityConnector().with { $0.serviceAgentEmail = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let serviceAgentEmail = CodingKeys(stringValue: "serviceAgentEmail")
    static let connectionState = CodingKeys(stringValue: "connectionState")

    static let _knownKeys: Set<Swift.String> = [
      "serviceAgentEmail",
      "connectionState",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAgentEmail) {
      self.serviceAgentEmail = value
    }
    if let value = try container.decodeIfPresent(
      IdentityConnector.ConnectionState.self, forKey: .connectionState)
    {
      self.connectionState = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.serviceAgentEmail, forKey: .serviceAgentEmail)
    try container.encode(self.connectionState, forKey: .connectionState)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The various connection states of the WorkloadIdentityPoolConnection.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ConnectionState: Codable, Equatable, Sendable {
    /// Default unspecified value.
    case unspecified
    /// The identity pool connection is connected.
    case connected
    /// The identity pool connection is partially connected.
    case partiallyConnected
    /// The identity pool connection is disconnected.
    case disconnected
    /// The identity pool connection is in an unknown state.
    case unknown
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .connected: return 1
      case .partiallyConnected: return 2
      case .disconnected: return 3
      case .unknown: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CONNECTION_STATE_UNSPECIFIED"
      case .connected: return "CONNECTED"
      case .partiallyConnected: return "PARTIALLY_CONNECTED"
      case .disconnected: return "DISCONNECTED"
      case .unknown: return "UNKNOWN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConnectionState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CONNECTION_STATE_UNSPECIFIED": self = .unspecified
      case "CONNECTED": self = .connected
      case "PARTIALLY_CONNECTED": self = .partiallyConnected
      case "DISCONNECTED": self = .disconnected
      case "UNKNOWN": self = .unknown
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConnectionState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .connected
      case 2: self = .partiallyConnected
      case 3: self = .disconnected
      case 4: self = .unknown
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CONNECTION_STATE_UNSPECIFIED")
      case .connected: return try container.encode("CONNECTED")
      case .partiallyConnected: return try container.encode("PARTIALLY_CONNECTED")
      case .disconnected: return try container.encode("DISCONNECTED")
      case .unknown: return try container.encode("UNKNOWN")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.IdentityConnector"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
