// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message for listing GoldengateDeploymentVersions.
public struct ListGoldengateDeploymentVersionsRequest: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// Required. Parent value for ListGoldengateDeploymentVersionsRequest
  /// Format: projects/{project}/locations/{location}
  public var parent: Swift.String = Swift.String()

  /// Optional. Requested page size. Server may return fewer items than
  /// requested. If unspecified, server will pick an appropriate default. The
  /// maximum value is 1000; values above 1000 will be coerced to 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A token identifying a page of results the server should return.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. An expression for filtering the results of the request. Either
  /// the deployment_id and deployment_type fields must be specified in the
  /// format: `deployment_id="id"` or `deployment_type="DATABASE_ORACLE"`.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListGoldengateDeploymentVersionsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListGoldengateDeploymentVersionsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.oracledatabase.v1.ListGoldengateDeploymentVersionsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
