// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The Polaris Iceberg catalog.
public struct PolarisIcebergCatalog: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The Polaris uri.
  public var uri: Swift.String = Swift.String()

  /// Required. The catalog name within Polaris.
  public var polarisCatalog: Swift.String = Swift.String()

  /// Required. The Polaris client ID.
  public var clientId: Swift.String = Swift.String()

  /// Required. The Polaris principal role.
  public var principalRole: Swift.String = Swift.String()

  /// Optional. The Polaris client secret.
  public var clientSecret: Swift.String = Swift.String()

  /// Initialize a new instance of `PolarisIcebergCatalog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PolarisIcebergCatalog().with { $0.uri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.PolarisIcebergCatalog"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
