// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request for `ExadbVmCluster.Update`. We only support adding the
/// Virtual Machine to the ExadbVmCluster. Rest of the fields in ExadbVmCluster
/// are immutable.
public struct UpdateExadbVmClusterRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. A mask specifying which fields in th VM Cluster should be
  /// updated. A field specified in the mask is overwritten. If a mask isn't
  /// provided then all the fields in the VM Cluster are overwritten.
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Required. The resource being updated.
  public var exadbVmCluster: ExadbVmCluster? = nil

  /// Optional. An optional ID to identify the request. This value is used to
  /// identify duplicate requests. If you make a request with the same request ID
  /// and the original request is still in progress or completed, the server
  /// ignores the second request. This prevents clients from
  /// accidentally creating duplicate commitments.
  ///
  /// The request ID must be a valid UUID with the exception that zero UUID is
  /// not supported (00000000-0000-0000-0000-000000000000).
  public var requestId: Swift.String = Swift.String()

  /// Initialize a new instance of `UpdateExadbVmClusterRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateExadbVmClusterRequest().with { $0.updateMask = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.oracledatabase.v1.UpdateExadbVmClusterRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
